import * as stylex from "@stylexjs/stylex";

export const catalogPageStyles = stylex.create({
  mobileOnly: {
    display: {
      default: "none",
      "@media (max-width: 760px)": "block",
    },
  },
  desktopOnly: {
    display: {
      default: "block",
      "@media (max-width: 760px)": "none",
    },
  },
  searchField: {
    display: "flex",
    flex: "1 1 auto",
    minWidth: 0,
    height: 40,
    alignItems: "center",
    gap: 4,
    padding: "8px 12px",
    borderRadius: 34,
    backgroundColor: "var(--color-bg-secondary)",
    color: "var(--color-fg-secondary)",
  },
  searchPlaceholder: {
    minWidth: 0,
    overflow: "hidden",
    fontSize: 16,
    fontWeight: 400,
    lineHeight: "24px",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  headerControl: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    padding: 0,
    borderWidth: 0,
    backgroundColor: "transparent",
    color: "var(--color-fg-primary)",
    fontSize: {
      default: 16,
      "@media (max-width: 760px)": 14,
    },
    fontWeight: 500,
    lineHeight: {
      default: "24px",
      "@media (max-width: 760px)": "20px",
    },
    whiteSpace: "nowrap",
  },
  mobileCatalogRoot: {
    minHeight: "100vh",
    paddingBottom: 56,
    backgroundColor: "var(--color-bg-primary)",
  },
  mobileRootHeader: {
    position: "sticky",
    top: 0,
    zIndex: 40,
    backgroundColor: "var(--color-bg-primary)",
  },
  mobileRootTop: {
    display: "flex",
    minHeight: 56,
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 8,
    paddingBottom: 8,
    backgroundColor: "var(--color-bg-primary)",
  },
  mobileBrand: {
    flex: "0 0 auto",
    color: "var(--color-fg-primary)",
    fontFamily: "var(--font-display)",
    fontSize: 24,
    fontWeight: 800,
    lineHeight: "32px",
  },
  mobileHeaderControls: {
    display: "flex",
    height: 40,
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 12,
  },
  mobileSearchRow: {
    display: "flex",
    minHeight: 56,
    alignItems: "flex-start",
    paddingTop: 8,
    paddingBottom: 8,
    backgroundColor: "var(--color-bg-primary)",
  },
  rootCategoriesSection: {
    width: "100%",
    padding: "7px 16px 16px",
  },
  rootCategoriesGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: 8,
  },
  rootCard: {
    position: "relative",
    display: "block",
    aspectRatio: "1 / 1",
    minHeight: 0,
    overflow: "hidden",
    borderRadius: 16,
    backgroundColor: "var(--color-bg-secondary)",
    color: "var(--color-fg-primary)",
  },
  rootCardTitle: {
    position: "absolute",
    top: 12,
    right: 12,
    left: 12,
    zIndex: 1,
    margin: 0,
    fontSize: 14,
    fontWeight: 500,
    lineHeight: "20px",
  },
  rootCardImageClip: {
    position: "absolute",
    inset: 0,
    overflow: "hidden",
    pointerEvents: "none",
  },
  rootCardImage: {
    position: "absolute",
    maxWidth: "none",
    objectFit: "contain",
    mixBlendMode: "darken",
  },
  rootCardImageMobile: {
    top: "18.64%",
    left: "13.11%",
    width: "104.24%",
    height: "104.24%",
  },
  rootCardImageComputers: {
    top: "22.04%",
    left: "21.03%",
    width: "100%",
    height: "100%",
  },
  rootCardImageTv: {
    top: "25.04%",
    left: "16.92%",
    width: "96.21%",
    height: "96.21%",
  },
  rootCardImagePhoto: {
    top: "25.54%",
    left: "20.53%",
    width: "100%",
    height: "100%",
  },
  rootCardImageHome: {
    top: "22.35%",
    left: "25.57%",
    width: "84.52%",
    height: "84.52%",
  },
  rootCardImageHealth: {
    top: "26.78%",
    left: "20.16%",
    width: "89.54%",
    height: "89.54%",
  },
  mobileDetailHeader: {
    position: "sticky",
    top: 0,
    zIndex: 40,
    backgroundColor: "var(--color-bg-primary)",
  },
  mobileDetailToolbar: {
    display: "flex",
    minHeight: 56,
    alignItems: "center",
    gap: 8,
    paddingTop: 8,
    paddingBottom: 8,
    backgroundColor: "var(--color-bg-primary)",
  },
  mobileTitleRow: {
    display: "flex",
    minHeight: 64,
    alignItems: "center",
    marginTop: 8,
    paddingTop: 16,
    paddingBottom: 16,
    backgroundColor: "var(--color-bg-primary)",
  },
  mobileTitle: {
    margin: 0,
    color: "var(--color-fg-primary)",
    fontSize: 24,
    fontWeight: 600,
    lineHeight: "32px",
    letterSpacing: 0,
  },
  mobileDetailContent: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
    paddingBottom: 32,
  },
  categorySection: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  groupHeader: {
    display: "flex",
    height: 48,
    flexDirection: "column",
    alignItems: "stretch",
  },
  groupHeaderRow: {
    display: "flex",
    minHeight: 47,
    alignItems: "center",
    overflow: "hidden",
    paddingTop: 12,
    paddingBottom: 11,
    backgroundColor: "var(--color-bg-primary)",
  },
  groupHeaderText: {
    margin: 0,
    color: "var(--color-fg-secondary)",
    fontSize: 14,
    fontWeight: 400,
    lineHeight: "20px",
  },
  groupHeaderBorder: {
    height: 1,
    backgroundColor: "var(--color-divider-light)",
  },
  links: {
    display: "flex",
    flexDirection: "column",
    alignItems: "stretch",
  },
  linkRow: {
    display: "flex",
    minHeight: 32,
    alignItems: "center",
    overflow: "hidden",
    paddingTop: 4,
    paddingBottom: 4,
    color: "var(--color-fg-primary)",
    fontSize: 16,
    fontWeight: 500,
    lineHeight: "24px",
  },
  tagsRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 4,
    alignItems: "center",
    overflow: "hidden",
    paddingTop: 8,
    paddingBottom: 8,
  },
  tag: {
    display: "inline-flex",
    flex: "0 0 auto",
    minHeight: 32,
    alignItems: "center",
    justifyContent: "center",
    padding: "6px 12px",
    borderRadius: 24,
    backgroundColor: "var(--color-bg-secondary)",
    color: "var(--color-fg-primary)",
    fontSize: 14,
    fontWeight: 500,
    lineHeight: "20px",
    whiteSpace: "pre",
  },
  detailDivider: {
    width: 292,
    maxWidth: "100%",
    height: 1,
    backgroundColor: "rgb(0 0 0 / 10%)",
  },
  desktopNavbar: {
    display: "flex",
    height: 72,
    alignItems: "center",
    gap: 24,
    padding: "16px 64px",
    backgroundColor: "var(--color-bg-primary)",
    boxShadow: "var(--shadow-navbar)",
  },
  desktopBrand: {
    flex: "0 0 auto",
    width: 99,
    color: "var(--color-fg-primary)",
    fontFamily: "var(--font-display)",
    fontSize: 28,
    fontWeight: 800,
    lineHeight: "40px",
  },
  desktopNavbarMain: {
    display: "flex",
    flex: "1 1 auto",
    minWidth: 0,
    alignItems: "center",
    gap: 8,
  },
  desktopCatalogButton: {
    display: "inline-flex",
    flex: "0 0 auto",
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    padding: "8px 16px 8px 12px",
    borderRadius: 34,
    backgroundColor: "var(--color-bg-dark)",
    color: "var(--color-fg-on-dark)",
    fontSize: 16,
    fontWeight: 500,
    lineHeight: "24px",
    whiteSpace: "nowrap",
  },
  desktopSearchBox: {
    display: "flex",
    flex: "1 1 auto",
    minWidth: 220,
  },
  desktopNavbarRight: {
    display: "flex",
    flex: "0 0 auto",
    alignItems: "center",
    gap: 16,
  },
  desktopActionButtons: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  desktopContent: {
    display: "grid",
    gridTemplateColumns: {
      default: "248px minmax(0, 1fr)",
      "@media (max-width: 1180px)": "224px minmax(0, 1fr)",
    },
    columnGap: {
      default: 60,
      "@media (max-width: 1180px)": 32,
    },
    maxWidth: 1440,
    marginInline: "auto",
    padding: {
      default: "24px 68px",
      "@media (max-width: 1180px)": "24px 32px",
    },
  },
  desktopAside: {
    display: "flex",
    flexDirection: "column",
    width: {
      default: 248,
      "@media (max-width: 1180px)": 224,
    },
  },
  desktopCategoryPanel: {
    display: "flex",
    height: 336,
    flexDirection: "column",
    overflow: "hidden",
    padding: "8px 4px 16px",
    borderRadius: 12,
    backgroundColor: "var(--color-bg-secondary)",
  },
  desktopSidebarHeading: {
    minHeight: 28,
    margin: 0,
    padding: "4px 12px",
    color: "var(--color-fg-secondary)",
    fontSize: 12,
    fontWeight: 400,
    lineHeight: "20px",
  },
  desktopSidebarRows: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  desktopSidebarRow: {
    display: "flex",
    minHeight: 40,
    alignItems: "center",
    gap: 8,
    overflow: "hidden",
    padding: "8px 12px",
    borderRadius: 8,
    color: "var(--color-fg-primary)",
    fontSize: 16,
    fontWeight: 500,
    lineHeight: "24px",
  },
  desktopSidebarRowSelected: {
    backgroundColor: "var(--color-bg-primary)",
  },
  desktopSidebarIcon: {
    flex: "0 0 auto",
    width: 24,
    height: 24,
    objectFit: "contain",
  },
  desktopPromo: {
    position: "relative",
    height: 256,
    marginTop: 87,
    overflow: "hidden",
    borderRadius: 12,
    backgroundColor: "var(--color-bg-dark)",
  },
  desktopPromoImage: {
    position: "absolute",
    inset: 0,
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  desktopPromoContent: {
    position: "relative",
    zIndex: 1,
    display: "flex",
    height: "100%",
    flexDirection: "column",
    alignItems: "flex-start",
    justifyContent: "space-between",
    padding: "24px 20px",
    color: "var(--color-fg-on-dark)",
  },
  desktopPromoText: {
    display: "flex",
    width: "100%",
    flexDirection: "column",
    gap: 4,
  },
  desktopPromoKicker: {
    margin: 0,
    fontSize: 12,
    fontWeight: 500,
    lineHeight: "20px",
  },
  desktopPromoTitle: {
    display: "flex",
    flexDirection: "column",
    margin: 0,
    fontSize: 18,
    fontWeight: 600,
    lineHeight: "24px",
    letterSpacing: 0,
  },
  desktopPromoButton: {
    display: "inline-flex",
    height: 40,
    alignItems: "center",
    padding: "8px 16px",
    borderRadius: 34,
    backgroundColor: "var(--color-bg-primary)",
    color: "var(--color-fg-primary)",
    fontSize: 16,
    fontWeight: 500,
    lineHeight: "24px",
    whiteSpace: "nowrap",
  },
  desktopMain: {
    minWidth: 0,
    paddingTop: 8,
  },
  desktopTitle: {
    margin: "0 0 24px",
    color: "var(--color-fg-primary)",
    fontSize: 28,
    fontWeight: 600,
    lineHeight: "40px",
    letterSpacing: 0,
  },
  desktopColumns: {
    display: "grid",
    gridTemplateColumns: {
      default: "repeat(3, minmax(0, 292px))",
      "@media (max-width: 1180px)": "repeat(2, minmax(0, 1fr))",
    },
    columnGap: {
      default: 60,
      "@media (max-width: 1180px)": 32,
    },
    rowGap: {
      default: 0,
      "@media (max-width: 1180px)": 32,
    },
    alignItems: "start",
  },
  desktopColumn: {
    display: "flex",
    flexDirection: "column",
    gap: 32,
    width: {
      default: 292,
      "@media (max-width: 1180px)": "auto",
    },
  },
  desktopColumnFirst: {
    gap: 32,
  },
  desktopColumnSecond: {
    gap: 48,
  },
});
