openapi: 3.0.3
info:
  title: marketi
  version: "1"
servers:
  - url: /api

paths:
  /catalog/categories:
    get:
      operationId: listCategories
      description: |
        Отсортированный список категорий со всеми подкатегориями
      parameters:
        - $ref: '#/components/parameters/AcceptLocale'
      responses:
        "200":
          $ref: '#/components/responses/CategoryListResponse'

  /catalog/products:
    get:
      operationId: listProducts
      description: |
        Список популярных продуктов.
      parameters:
        - $ref: '#/components/parameters/AcceptLocale'
        - name: ids
          in: query
          required: false
          explode: false
          schema:
            type: array
            items:
              type: string
              format: uuid
        - name: limit
          required: true
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 50
        - name: sort
          required: false
          in: query
          schema:
            $ref: '#/components/schemas/ProductSort'
        - name: sortOrder
          required: false
          in: query
          schema:
            $ref: '#/components/schemas/SortOrder'
        - name: cursor
          required: false
          in: query
          schema:
            type: string
      responses:
        "200":
          $ref: '#/components/responses/ProductListResponse'
        "400":
          $ref: '#/components/responses/ErrorResponse'

  /catalog/products/{id}:
    get:
      operationId: getProduct
      description: |
        Детальная карточка продукта
      parameters:
        - $ref: '#/components/parameters/AcceptLocale'
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          required: true
      responses:
        "200":
          $ref: '#/components/responses/ProductResponse'
        "400":
          $ref: '#/components/responses/ErrorResponse'

  /catalog/search:
    get:
      operationId: searchProducts
      description: |
        Поиск продуктов по тексту и/или фильтрам.
        Продукты всегда возвращаются в рамках одной из категорий для поддержания корректности
        фильтров. Также возвращаются возможные категории продуктов и выбранная категория,
        по которой происходит поиск.

        При запросе с фильтрами всегда необходимо указывать категорию.

        Возможные фильтры, их названия и типы полностью определяются тем, что ответил сервер.
        Поэтому они не указаны как параметры запроса в схеме. Каждый тип фильтра соотносится типа параметра, который фильтруется.
        Каждый фильтр в ответе имеет указатель на то, были ли выбраны какие-то значения для этого фильтра при запросе.
        Так на стороне клиента должны отсекаться невалидные значения, сужения фильтров и так далее: логика формирования фильтров
        и действующих значений полностью находится на стороне сервера.

        Правила наименований фильтров при использовании в запросе:
          - Типы фильтров: `checkbox`, `range`, `toggle`.
          - `checkbox`: фильтры предполагают выбор нескольких предложенных значений.
          В качестве сепаратора значения использовать `,`, например: `brand=Apple,Samsung'
          - `range`: фильтр предполагает выбор из минимального и максимального значения какого-то числового
          параметра для поиска. `min` и `max` из ответа указывают на минимальные и максимальные значения по всему корпусу.
          При применении данного фильтра необходимо **всегда присылать оба значения** в виде: `{selectedMin}-{selectedMax}`,
          заменяя невыбранные границами всего корпуса, которые пришли в ответе.
          - `toggle`: простой фильтр `true/false`. Отправлять как `true/false`.
      parameters:
        - $ref: '#/components/parameters/AcceptLocale'
        - name: q
          in: query
          description: Текст запроса
          required: false
          schema:
            type: string
        - name: category
          in: query
          description: Категория поиска. Принимаются только конечные категории
          required: false
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
        - name: sort
          in: query
          schema:
            $ref: '#/components/schemas/ProductSort'
        - name: sortOrder
          in: query
          description: Направление сортировки. По умолчанию - по убыванию
          schema:
            $ref: '#/components/schemas/SortOrder'
        - name: cursor
          in: query
          schema:
            type: string
      responses:
        "200":
          $ref: '#/components/responses/SearchResponse'

  /catalog/search/suggest:
    get:
      operationId: listSuggestions
      description: |
        Подсказки для поиска
      parameters:
        - $ref: '#/components/parameters/AcceptLocale'
        - name: q
          in: query
          description: Текст запроса
          required: true
          schema:
            type: string
        - name: limit
          in: query
          required: true
          schema:
            type: integer
            minimum: 1
            maximum: 50
      responses:
        "200":
          $ref: '#/components/responses/SearchSuggestionResponse'

components:
  responses:
    ErrorResponse:
      description: Общая ошибка
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    CategoryListResponse:
      description: Список категорий
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CategoryList'

    ProductListResponse:
      description: Список продуктов
      content:
        application/json:
          schema:
            type: object
            required: [cursor, products]
            properties:
              cursor:
                $ref: '#/components/schemas/Cursor'
              products:
                $ref: '#/components/schemas/ProductList'

    SearchResponse:
      description: |
        Список продуктов по запросу, подходящих категорий и фильтров
        по выбранной или предсказанной категории.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SearchResponse'

    SearchSuggestionResponse:
      description: |
        Подсказки содержат ID, отображаемое название и тип сущности,
        к которой они относятся. Актуальный набор типов сущностей указан
        в схеме подсказки
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SearchSuggestion'

    ProductResponse:
      description: |
        Детальная карточка продукта
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Product'

  parameters:
    AcceptLocale:
      name: "Accept-Locale"
      in: header
      required: false
      schema:
        type: string
        enum: [ru, en, ka]
        x-go-type: domain.Language

  schemas:
    Error:
      type: object
      required: [code, message]
      properties:
        code:
          type: string
        message:
          type: string
        data:
          type: object
          additionalProperties: true

    Cursor:
      type: object
      x-go-type: paging.Cursor
      properties:
        next:
          type: string
          nullable: true
        prev:
          type: string
          nullable: true

    CategoryList:
      type: array
      items:
        $ref: '#/components/schemas/Category'

    Category:
      type: object
      required: [id, label, imageUrl, type]
      properties:
        id:
          type: string
        type:
          type: string
          enum: [normal, button]
        label:
          type: string
        imageUrl:
          type: string
          format: null-string
          nullable: true
        subCategories:
          type: array
          items:
            $ref: '#/components/schemas/Category'

    ProductList:
      type: array
      items:
        $ref: '#/components/schemas/ProductListItem'

    ProductListItem:
      type: object
      required: [id, name, minPriceTetri, offersCount, imageUrls, isNew]
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        minPriceTetri:
          type: integer
        offersCount:
          type: integer
        imageUrls:
          type: array
          items:
            type: string
        isNew:
          type: boolean

    SearchSuggestionItem:
      type: object
      required: [id, label, type]
      properties:
        id:
          type: string
        label:
          type: string
        type:
          type: string
          enum: [product, category]

    SearchSuggestion:
      type: object
      required: [suggestions]
      properties:
        suggestions:
          type: array
          items:
            $ref: '#/components/schemas/SearchSuggestionItem'

    SearchResponse:
      type: object
      required: [title, products, filters, categories, cursor]
      properties:
        title:
          type: string
        products:
          $ref: '#/components/schemas/ProductList'
        filters:
          type: array
          items:
            $ref: '#/components/schemas/SearchFilter'
        categories:
          type: array
          items:
            $ref: '#/components/schemas/SearchCategory'
        cursor:
          $ref: '#/components/schemas/Cursor'

    SearchCategory:
      type: object
      required: [id, label, selected, imageUrl]
      properties:
        id:
          type: string
        label:
          type: string
        selected:
          type: boolean
        imageUrl:
          type: string
          format: url
          x-go-type: null.String

    SearchFilter:
      type: object
      required: [type]
      oneOf:
        - $ref: '#/components/schemas/SearchFilterRange'
        - $ref: '#/components/schemas/SearchFilterSelectable'
      discriminator:
        propertyName: type
        mapping:
          checkbox: '#/components/schemas/SearchFilterSelectable'
          toggle: '#/components/schemas/SearchFilterSelectable'
          range: '#/components/schemas/SearchFilterRange'

    SearchFilterType:
      type: string
      enum: [checkbox, toggle, range]

    SearchFilterVariant:
      type: object
      required: [value, label, selected]
      properties:
        value:
          type: string
        label:
          type: string
        selected:
          type: boolean

    SearchFilterSelectable:
      type: object
      required: [type, id, label, variants]
      properties:
        type:
          type: string
          enum: [checkbox, toggle]
        id:
          type: string
        label:
          type: string
        variants:
          type: array
          items:
            $ref: '#/components/schemas/SearchFilterVariant'

    SearchFilterRange:
      type: object
      required: [type, id, label, min, max, selectedMin, selectedMax]
      properties:
        type:
          type: string
          enum: [range]
        id:
          type: string
        label:
          type: string
        min:
          type: integer
        max:
          type: integer
        selectedMin:
          type: integer
        selectedMax:
          type: integer

    Product:
      type: object
      required: [id, name, isNew, description, imageUrls, offers, attributes, categoryBreadcrumbs, variants]
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        imageUrls:
          type: array
          items:
            type: string
        isNew:
          type: boolean
        categoryBreadcrumbs:
          type: array
          items:
            type: string
        offers:
          type: array
          items:
            $ref: '#/components/schemas/ProductOffer'
        attributes:
          $ref: '#/components/schemas/ProductAttributeList'
        variants:
          type: array
          items:
            $ref: '#/components/schemas/ProductVariantGroup'

    ProductVariantGroup:
      type: object
      required: [label, options]
      properties:
        label:
          type: string
        options:
          type: array
          items:
            $ref: '#/components/schemas/ProductVariantOption'

    ProductVariantOption:
      type: object
      required: [productId, label, selected, exact]
      properties:
        productId:
          type: string
          format: uuid
        label:
          type: string
        selected:
          type: boolean
        exact:
          type: boolean

    ProductOffer:
      type: object
      required: [merchant, url, priceTetri, originalPriceTetri, ratioToBestPrice]
      properties:
        merchant:
          $ref: '#/components/schemas/ProductOfferMerchant'
        url:
          type: string
        priceTetri:
          type: integer
        originalPriceTetri:
          type: integer
        ratioToBestPrice:
          type: number
          format: float

    ProductOfferMerchant:
      type: object
      required: [name, url, logoUrl, phone]
      properties:
        name:
          type: string
        url:
          type: string
        logoUrl:
          type: string
        phone:
          type: string
          format: null-string

    ProductAttributeList:
      type: object
      required: [groups]
      properties:
        groups:
          type: array
          items:
            $ref: '#/components/schemas/ProductAttributeGroup'

    ProductAttributeGroup:
      type: object
      required: [label, attributes]
      properties:
        label:
          type: string
        attributes:
          type: array
          items:
            $ref: '#/components/schemas/ProductAttribute'

    ProductAttribute:
      type: object
      required: [label, value]
      properties:
        label:
          type: string
        value:
          type: string

    ProductSort:
      type: string
      enum: [popularity, price]
      default: price
      x-go-type: domain.ProductSort

    SortOrder:
      type: string
      enum: [asc, desc]
      default: asc
      x-go-type: paging.Order
