/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * marketi
 * OpenAPI spec version: 1
 */

export type AcceptLocaleParameter =
  (typeof AcceptLocaleParameter)[keyof typeof AcceptLocaleParameter];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AcceptLocaleParameter = {
  ru: "ru",
  en: "en",
  ka: "ka",
} as const;
