/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * marketi
 * OpenAPI spec version: 1
 */
import type { CategoryType } from "./categoryType";

export interface Category {
  id: string;
  type: CategoryType;
  label: string;
  /** @nullable */
  imageUrl: string | null;
  subCategories?: Category[];
}
