/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * marketi
 * OpenAPI spec version: 1
 */

export type CategoryType = (typeof CategoryType)[keyof typeof CategoryType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CategoryType = {
  normal: "normal",
  button: "button",
} as const;
