/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */

/**
 * Display only; nothing queries by it.
 * @nullable
 */
export type Coords = {
  lat: number;
  lon: number;
} | null;
