/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { CrmAttribute } from "./crmAttribute";

export interface CrmAttributeSaved {
  attribute: CrmAttribute;
  /** A rehash per product type the edit invalidated. */
  run_ids: string[];
}
