/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */

export type CrmAttributeValueType =
  (typeof CrmAttributeValueType)[keyof typeof CrmAttributeValueType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CrmAttributeValueType = {
  enum: "enum",
  string: "string",
  int: "int",
  decimal: "decimal",
  bool: "bool",
  set: "set",
} as const;
