/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { CrmAttributeAliasEntry } from "./crmAttributeAliasEntry";

export interface CrmAttributeAliased {
  aliases: CrmAttributeAliasEntry[];
  /** The rematch each aliased value enqueued. */
  run_ids: string[];
}
