/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { CrmAttributeValueType } from "./crmAttributeValueType";

export interface CrmAttribute {
  code: string;
  value_type: CrmAttributeValueType;
  /** Empty on everything but a numeric attribute. */
  unit: string;
  /** What the model reads to decide what the attribute means. */
  description: string;
  /** The codes an enumerated attribute accepts, in their order, empty
otherwise.
 */
  enum_values: string[];
}
