/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { CrmAttributeValue } from "./crmAttributeValue";

export interface CrmAttributeValues {
  attribute_code: string;
  values: CrmAttributeValue[];
}
