/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { CrmAttributeEditValueType } from "./crmAttributeEditValueType";

export interface CrmAttributeEdit {
  value_type: CrmAttributeEditValueType;
  unit: string;
  description: string;
  /** Replaces the stored list; order is the order given. */
  enum_values: string[];
}
