/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */

export interface CrmAlias {
  attribute_code: string;
  /** The folded published value the alias corrects. */
  from_fold: string;
  /** The canonical value, in display form. */
  to_display: string;
}
