/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */

export interface CrmAttributeAlias {
  /** The canonical value, in display form. */
  to_display: string;
  /** Observed values, as the distribution reports them. */
  from_values: string[];
}
