/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */

export interface CrmAttributeValue {
  /** As a shop published it. */
  value: string;
  /** The key an alias for this value is written under. Two published
values sharing one fold already resolve alike.
 */
  fold: string;
  offer_count: number;
  /**
   * What matching resolves the value to, null where no alias does.
   * @nullable
   */
  canonical: string | null;
}
