/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { CrmBindingEditRole } from "./crmBindingEditRole";
import type { CrmBindingEditFilterType } from "./crmBindingEditFilterType";
import type { CrmRoleOverrideEdit } from "./crmRoleOverrideEdit";

export interface CrmBindingEdit {
  role: CrmBindingEditRole;
  sort_order: number;
  is_filterable: boolean;
  /** Empty exactly while the attribute is not filterable. */
  filter_type: CrmBindingEditFilterType;
  /** Replaces the stored list: an override this does not state is one the
binding no longer carries. Scope values are folded server-side.
 */
  overrides: CrmRoleOverrideEdit[];
}
