/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { CrmBindingRole } from "./crmBindingRole";
import type { CrmBindingFilterType } from "./crmBindingFilterType";
import type { CrmRoleOverride } from "./crmRoleOverride";

export interface CrmBinding {
  product_type_code: string;
  attribute_code: string;
  role: CrmBindingRole;
  /** For an axis, the order a picker offers it in. */
  sort_order: number;
  is_filterable: boolean;
  /** Empty exactly while the attribute is not filterable. */
  filter_type: CrmBindingFilterType;
  /** The role overrides that amend this binding, in scope order. They are
part of the binding rather than an entity beside it.
 */
  overrides: CrmRoleOverride[];
}
