/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */

export type CrmBindingEditRole =
  (typeof CrmBindingEditRole)[keyof typeof CrmBindingEditRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CrmBindingEditRole = {
  common: "common",
  identity: "identity",
  variant: "variant",
} as const;
