/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */

/**
 * Empty exactly while the attribute is not filterable.
 */
export type CrmBindingEditFilterType =
  (typeof CrmBindingEditFilterType)[keyof typeof CrmBindingEditFilterType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CrmBindingEditFilterType = {
  "": "",
  pick: "pick",
  range: "range",
} as const;
