/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */

export type CrmBindingRole =
  (typeof CrmBindingRole)[keyof typeof CrmBindingRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CrmBindingRole = {
  common: "common",
  identity: "identity",
  variant: "variant",
} as const;
