/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */

export interface CrmCategory {
  code: string;
  /** @nullable */
  parent_code: string | null;
  path: string;
  sort_order: number;
}
