/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */

export interface CrmCategoryEdit {
  /** Empty for a root. */
  parent_code: string;
  sort_order: number;
}
