/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { CrmDivergence } from "./crmDivergence";

export interface CrmDivergenceList {
  attribute_code: string;
  identities: CrmDivergence[];
}
