/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { CrmValueCount } from "./crmValueCount";

export interface CrmDivergence {
  identity_hash: string;
  name: string;
  /** Values the offers of one configuration contradict each other with,
counted over offers.
 */
  within: CrmValueCount[];
  /** Values that separate one configuration of the group from another,
counted over configurations.
 */
  across: CrmValueCount[];
}
