/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { AttributeValues } from "./attributeValues";
import type { AttributeValue } from "./attributeValue";

export interface CrmFork {
  product_type_code: string;
  identity_hash: string;
  /** The axis that forked, which an override would demote. */
  attribute_code: string;
  /** The identity values the group shares, one of which is the scope an
override is written against.
 */
  identity: AttributeValues;
  /** One configuration's name, so the group is recognisable. */
  name: string;
  silent_count: number;
  stating_count: number;
  stated_values: AttributeValue[];
}
