/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { CrmFork } from "./crmFork";

export interface CrmForkList {
  product_type_code: string;
  forks: CrmFork[];
}
