/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { JobRunKind } from "./jobRunKind";
import type { JobRunStatus } from "./jobRunStatus";
import type { CrmJobRunScope } from "./crmJobRunScope";
import type { CrmJobRunStatsProperty } from "./crmJobRunStatsProperty";

export interface CrmJobRun {
  id: string;
  kind: JobRunKind;
  status: JobRunStatus;
  scope: CrmJobRunScope;
  /** Kind-specific counters, empty until a run records one. */
  stats: CrmJobRunStatsProperty;
  created_at: string;
  /**
   * Null until the run runs.
   * @nullable
   */
  started_at: string | null;
  /** @nullable */
  finished_at: string | null;
  /** Empty unless the run failed. */
  error: string;
}
