/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { JobRunStatus } from "./jobRunStatus";

export interface CrmJobRunStatusCount {
  status: JobRunStatus;
  count: number;
}
