/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { CrmJobRunStatusCount } from "./crmJobRunStatusCount";
import type { CrmJobRunKindCount } from "./crmJobRunKindCount";

/**
 * Counts over the whole filtered set, paging aside.
 */
export interface CrmJobRunStats {
  by_status: CrmJobRunStatusCount[];
  by_kind: CrmJobRunKindCount[];
}
