/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { CrmJobRun } from "./crmJobRun";
import type { CrmJobRunStats } from "./crmJobRunStats";

export interface CrmJobRunList {
  runs: CrmJobRun[];
  page: number;
  per_page: number;
  /** Every run the filter matches, which page numbers count. */
  total: number;
  stats: CrmJobRunStats;
}
