/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */

/**
 * What the run acts on. Which fields are stated follows from the kind.
 */
export interface CrmJobRunScope {
  /** @nullable */
  scrape_target_id: string | null;
  /** @nullable */
  product_type_code: string | null;
  /** @nullable */
  shop_code: string | null;
  /** @nullable */
  attribute_code: string | null;
  /** @nullable */
  from_fold: string | null;
}
