/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */

/**
 * Kind-specific counters, empty until a run records one.
 */
export type CrmJobRunStatsProperty = { [key: string]: number };
