/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { JobRunKind } from "./jobRunKind";

export interface CrmJobRunCancel {
  /** Empty cancels every unfinished run. */
  kinds: JobRunKind[];
}
