/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { AttributeValues } from "./attributeValues";

export interface CrmOfferEdit {
  name: string;
  description: string;
  /** Replaces the stored set: an attribute this does not state is one the
offer no longer carries.
 */
  attributes: AttributeValues;
}
