/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { CrmOfferDetail } from "./crmOfferDetail";

/**
 * The offer, its type's schema, and where it can go next.
 */
export type CrmOfferCardResponse = CrmOfferDetail;
