/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { OfferStatus } from "./offerStatus";

export interface CrmOffer {
  id: string;
  shop_code: string;
  /**
   * Null where the shop's keys map to none and its target declares none.
   * @nullable
   */
  product_type_code: string | null;
  /** The shop's own nodes, in its order, opaque to us. */
  shop_taxonomy_keys: string[];
  status: OfferStatus;
  /** Empty outside review. */
  review_reason: string;
  /** Empty while available. */
  unavailable_reason: string;
  name: string;
  url: string;
  /** @nullable */
  thumbnail_url: string | null;
  price_tetri: number;
  is_available: boolean;
  is_locked: boolean;
  /**
   * Null until the offer is matched.
   * @nullable
   */
  product_id: string | null;
  created_at: string;
  updated_at: string;
}
