/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { CrmOffer } from "./crmOffer";
import type { AttributeValues } from "./attributeValues";
import type { CrmTypeAttribute } from "./crmTypeAttribute";
import type { OfferStatus } from "./offerStatus";
import type { CrmProductOffer } from "./crmProductOffer";

export interface CrmOfferDetail {
  offer: CrmOffer;
  description: string;
  picture_urls: string[];
  /** This offer's normalized values, absent where nothing was stated. */
  attributes: AttributeValues;
  /** The product type's bindings with this offer's role overrides
applied, so an axis its brand does not vary is absent rather than
unstated. Empty where the offer resolves to no type.
 */
  type_attributes: CrmTypeAttribute[];
  /** The review transitions this offer's status allows. */
  transitions: OfferStatus[];
  /** The name of the product row this offer sits on, empty until it is
matched. Its id is the offer's `product_id`.
 */
  product_name: string;
  /** Every offer matched to that row, this one among them, ordered by
price. A hidden shop's offer is not in it.
 */
  product_offers: CrmProductOffer[];
}
