/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { CrmOverrideRole } from "./crmOverrideRole";

export interface CrmOverride {
  product_type_code: string;
  attribute_code: string;
  /** An identity attribute of the same product type. */
  scope_attribute_code: string;
  /** The folded value, which is the form a product key carries. */
  scope_value_fold: string;
  /** What the attribute becomes for the rows in scope. */
  role: CrmOverrideRole;
}
