/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { CrmOffer } from "./crmOffer";

export interface CrmOfferList {
  offers: CrmOffer[];
  page: number;
  per_page: number;
  /** Every offer the filter matches, which page numbers count. */
  total: number;
}
