/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { CrmProduct } from "./crmProduct";

export interface CrmProductList {
  products: CrmProduct[];
  page: number;
  per_page: number;
  /** Every row the filter matches, which page numbers count. */
  total: number;
}
