/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { CrmProductType } from "./crmProductType";

export interface CrmProductTypeList {
  product_types: CrmProductType[];
}
