/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */

export interface CrmProductType {
  code: string;
  name: string;
  /** `{attribute_code}` tokens. It must name every axis the type binds,
or two configurations render one name at two prices.
 */
  product_name_template: string;
  /** The browse categories every product of the type sits under. */
  category_codes: string[];
}
