/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { AttributeValues } from "./attributeValues";

export interface CrmProduct {
  id: string;
  product_type_code: string;
  /** What groups this row with its siblings. */
  identity_hash: string;
  name: string;
  /** @nullable */
  thumbnail_url: string | null;
  /** This configuration's own values, axes among them. */
  attributes: AttributeValues;
  /**
   * Null while no visible shop has it available.
   * @nullable
   */
  min_price_tetri: number | null;
  has_available_offer: boolean;
  is_locked: boolean;
  /** Every offer linked to the row. Zero is what deletes. */
  offer_count: number;
  created_at: string;
  updated_at: string;
}
