/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { OfferStatus } from "./offerStatus";

export interface CrmProductOffer {
  id: string;
  shop_code: string;
  status: OfferStatus;
  price_tetri: number;
  is_available: boolean;
}
