/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { CrmProductType } from "./crmProductType";

export interface CrmProductTypeSaved {
  product_type: CrmProductType;
  /** The rename an edited template enqueued. */
  run_ids: string[];
}
