/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */

export interface CrmProductTypeEdit {
  name: string;
  product_name_template: string;
  /** Replaces the stored list. */
  category_codes: string[];
}
