/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */

/**
 * What the attribute becomes for the rows in scope.
 */
export type CrmRoleOverrideRole =
  (typeof CrmRoleOverrideRole)[keyof typeof CrmRoleOverrideRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CrmRoleOverrideRole = {
  common: "common",
  variant: "variant",
} as const;
