/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { CrmRoleOverrideEditRole } from "./crmRoleOverrideEditRole";

export interface CrmRoleOverrideEdit {
  scope_attribute_code: string;
  /** As a shop published it; the endpoint folds it. */
  scope_value: string;
  role: CrmRoleOverrideEditRole;
}
