/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */

export type CrmRoleOverrideEditRole =
  (typeof CrmRoleOverrideEditRole)[keyof typeof CrmRoleOverrideEditRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CrmRoleOverrideEditRole = {
  common: "common",
  variant: "variant",
} as const;
