/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { CrmScrapeTarget } from "./crmScrapeTarget";

export interface CrmScrapeTargetSaved {
  target: CrmScrapeTarget;
  /** Empty; a target edit invalidates no derived membership. */
  run_ids: string[];
}
