/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { CrmSilence } from "./crmSilence";

export interface CrmSilenceList {
  shop_code: string;
  attributes: CrmSilence[];
}
