/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */

export type CrmScrapeTargetFetchMode =
  (typeof CrmScrapeTargetFetchMode)[keyof typeof CrmScrapeTargetFetchMode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CrmScrapeTargetFetchMode = {
  api: "api",
  http: "http",
  browser: "browser",
} as const;
