/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { CrmScrapeTargetFetchMode } from "./crmScrapeTargetFetchMode";
import type { AttributeValues } from "./attributeValues";

export interface CrmScrapeTarget {
  id: string;
  shop_code: string;
  url: string;
  fetch_mode: CrmScrapeTargetFetchMode;
  /** Operator-asserted facts the shop does not publish, applied after
parsing and never entering an offer's raw attributes.
 */
  static_attributes: AttributeValues;
  /**
   * What an offer of this target takes where the shop's own keys map to
no type. Null leaves such an offer in review.

   * @nullable
   */
  product_type_code: string | null;
  is_enabled: boolean;
  /** Zero paginates to exhaustion. */
  max_pages: number;
}
