/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { Coords } from "./coords";

export interface CrmShopEdit {
  name: string;
  is_scraped: boolean;
  is_visible: boolean;
  priority: number;
  url: string;
  logo_url: string;
  address: string;
  phone_number: string;
  coords: Coords;
}
