/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { CrmScrapeTargetEditFetchMode } from "./crmScrapeTargetEditFetchMode";
import type { AttributeValues } from "./attributeValues";

export interface CrmScrapeTargetEdit {
  shop_code: string;
  url: string;
  fetch_mode: CrmScrapeTargetEditFetchMode;
  static_attributes: AttributeValues;
  /** @nullable */
  product_type_code: string | null;
  is_enabled: boolean;
  max_pages: number;
}
