/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */

export type CrmScrapeTargetEditFetchMode =
  (typeof CrmScrapeTargetEditFetchMode)[keyof typeof CrmScrapeTargetEditFetchMode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CrmScrapeTargetEditFetchMode = {
  api: "api",
  http: "http",
  browser: "browser",
} as const;
