/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */

export interface CrmSilence {
  attribute_code: string;
  /** The shop's offers past parsing under types binding it. */
  offer_count: number;
  filled_count: number;
}
