/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { CrmTypeAttributeRole } from "./crmTypeAttributeRole";
import type { CrmTypeAttributeValueType } from "./crmTypeAttributeValueType";

export interface CrmTypeAttribute {
  code: string;
  role: CrmTypeAttributeRole;
  value_type: CrmTypeAttributeValueType;
  /** Empty on everything but a numeric attribute. */
  unit: string;
  /** The codes an enumerated attribute accepts, empty otherwise. */
  enum_values: string[];
}
