/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { CrmTaxonomy } from "./crmTaxonomy";

export interface CrmTaxonomyList {
  mappings: CrmTaxonomy[];
}
