/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */

export type CrmTypeAttributeRole =
  (typeof CrmTypeAttributeRole)[keyof typeof CrmTypeAttributeRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CrmTypeAttributeRole = {
  common: "common",
  identity: "identity",
  variant: "variant",
} as const;
