/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */

export interface CrmTaxonomyEdit {
  key: string;
  product_type_code: string;
  /** Empty where the key says nothing about where a customer browses. */
  category_code: string;
}
