/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */

export interface CrmTaxonomy {
  shop_code: string;
  /** The shop's own node, as it publishes it. */
  key: string;
  product_type_code: string;
  /**
   * Null where the key says nothing about where a customer browses.
   * @nullable
   */
  category_code: string | null;
}
