/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { CrmUnmappedKey } from "./crmUnmappedKey";

export interface CrmUnmappedKeyList {
  keys: CrmUnmappedKey[];
}
