/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { AttributeValue } from "./attributeValue";

export interface CrmValueCount {
  value: AttributeValue;
  count: number;
}
