/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * marketi
 * OpenAPI spec version: 1
 */
import type { ErrorErrorData } from "./errorErrorData";

export type ErrorError = {
  id: string;
  message: string;
  data?: ErrorErrorData;
};
