/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */

export type ErrorBodyKind = (typeof ErrorBodyKind)[keyof typeof ErrorBodyKind];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ErrorBodyKind = {
  invalid: "invalid",
  not_found: "not_found",
  conflict: "conflict",
  internal: "internal",
} as const;
