/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { ErrorBody } from "./errorBody";

export interface ErrorEnvelope {
  error: ErrorBody;
}
