/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * marketi
 * OpenAPI spec version: 1
 */
import type { ErrorData } from "./errorData";

export interface Error {
  code: string;
  message: string;
  data?: ErrorData;
}
