/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { ErrorBodyKind } from "./errorBodyKind";
import type { ErrorBodyDetails } from "./errorBodyDetails";

export interface ErrorBody {
  kind: ErrorBodyKind;
  code: string;
  message: string;
  details?: ErrorBodyDetails;
}
