/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { FacetValue } from "./facetValue";

export interface Facet {
  attribute_code: string;
  values: FacetValue[];
}
