/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */

export type JobRunKind = (typeof JobRunKind)[keyof typeof JobRunKind];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const JobRunKind = {
  scrape_target: "scrape_target",
  rehash: "rehash",
  rematch: "rematch",
  rename: "rename",
  recompute_categories: "recompute_categories",
} as const;
