/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */

export type JobRunStatus = (typeof JobRunStatus)[keyof typeof JobRunStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const JobRunStatus = {
  pending: "pending",
  running: "running",
  completed: "completed",
  failed: "failed",
  cancelled: "cancelled",
} as const;
