/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * marketi
 * OpenAPI spec version: 1
 */

export type ListSuggestionsParams = {
  /**
   * Текст запроса
   */
  q: string;
  /**
   * @minimum 1
   * @maximum 50
   */
  limit: number;
};
