/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * marketi
 * OpenAPI spec version: 1
 */

export type ListProductsParams = {
  ids?: string[];
  /**
   * @minimum 1
   * @maximum 50
   */
  limit: number;
  /**
   * @minimum 0
   * @maximum 50
   */
  page: number;
};
