/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */

export type ListCrmProductsParams = {
  /**
 * The category and every descendant of it, over both membership
branches: the row's type is mapped to one, or the row is attached to
one.

 */
  category?: string;
  product_type?: string;
  /**
 * One identity group, which is how a chosen row's siblings are read
(DESIGN.md §3.1).

 */
  identity?: string;
  min_price?: number;
  max_price?: number;
  /**
   * False is the manual delete flow's filter.
   */
  has_offers?: boolean;
  /**
   * 1-based.
   */
  page?: number;
  per_page?: number;
};
