/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { OfferStatus } from "./offerStatus";
import type { OfferReviewReason } from "./offerReviewReason";

export type ListCrmOffersParams = {
  status?: OfferStatus[];
  review_reason?: OfferReviewReason[];
  /**
   * Shop codes, which are data rather than a fixed list.
   */
  shop?: string[];
  /**
 * The category and every descendant of it, resolved through the
product types mapped to them.

 */
  category?: string;
  /**
   * Whether the offer carries a product link.
   */
  matched?: boolean;
  locked?: boolean;
  available?: boolean;
  min_price?: number;
  max_price?: number;
  updated_from?: string;
  updated_to?: string;
  /**
   * Free text over the offer's name and url.
   */
  q?: string;
  /**
   * 1-based.
   */
  page?: number;
  per_page?: number;
};
