/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { ListProductsSort } from "./listProductsSort";

export type ListProductsParams = {
  /**
   * Required unless q is given.
   */
  category?: string;
  /**
 * Matches a product name by containment. At least two characters, and
the only thing that makes `category` optional.

 */
  q?: string;
  min_price?: number;
  max_price?: number;
  /**
   * Defaults to price_asc.
   */
  sort?: ListProductsSort;
  limit?: number;
  /**
 * Opaque, and only ever a next_cursor of this endpoint. It carries the
sort it was read under, so a page continues that order or is refused.

 */
  cursor?: string;
};
