/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { JobRunKind } from "./jobRunKind";
import type { JobRunStatus } from "./jobRunStatus";

export type ListCrmJobRunsParams = {
  kind?: JobRunKind[];
  status?: JobRunStatus[];
  /**
   * The scope of a scrape run.
   */
  scrape_target?: string;
  /**
   * The scope of a rehash or a rename.
   */
  product_type?: string;
  created_from?: string;
  created_to?: string;
  /**
   * 1-based.
   */
  page?: number;
  per_page?: number;
};
