/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */

export type ListProductsSort =
  (typeof ListProductsSort)[keyof typeof ListProductsSort];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListProductsSort = {
  price_asc: "price_asc",
  price_desc: "price_desc",
  newest: "newest",
} as const;
