/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * marketi
 * OpenAPI spec version: 1
 */
import type { ProductSort } from "./productSort";
import type { SortOrder } from "./sortOrder";

export type ListProductsParams = {
  ids?: number[];
  /**
   * @minimum 1
   * @maximum 50
   */
  limit: number;
  sort?: ProductSort;
  sortOrder?: SortOrder;
  cursor?: string;
};
