/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */

export type OfferReviewReason =
  (typeof OfferReviewReason)[keyof typeof OfferReviewReason];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OfferReviewReason = {
  type_unresolved: "type_unresolved",
  identity_missing: "identity_missing",
  parse_failed: "parse_failed",
  enum_violation: "enum_violation",
  manual: "manual",
} as const;
