/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */

export type OfferStatus = (typeof OfferStatus)[keyof typeof OfferStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OfferStatus = {
  pending: "pending",
  parsed: "parsed",
  matched: "matched",
  review: "review",
  denied: "denied",
} as const;
