/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { Shop } from "./shop";

export interface Offer {
  id: string;
  shop: Shop;
  url: string;
  price_tetri: number;
  is_available: boolean;
}
