/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * marketi
 * OpenAPI spec version: 1
 */
import type { ProductOfferMerchant } from "./productOfferMerchant";

export interface ProductOffer {
  id: number;
  merchant: ProductOfferMerchant;
  url: string;
  updatedAt: string;
  priceTetri: number;
  originalPriceTetri: number;
  ratioToBestPrice: number;
}
