/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * marketi
 * OpenAPI spec version: 1
 */
import type { ProductVariantOption } from "./productVariantOption";

export interface ProductVariantGroup {
  id: string;
  label: string;
  options: ProductVariantOption[];
}
