/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { ProductTypeAttribute } from "./productTypeAttribute";

export interface ProductType {
  code: string;
  name: string;
  attributes: ProductTypeAttribute[];
}
