/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * marketi
 * OpenAPI spec version: 1
 */
import type { ProductList } from "./productList";

export type ProductListResponseResponse = {
  products?: ProductList;
};
