/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { ProductTypeAttributeRole } from "./productTypeAttributeRole";
import type { ProductTypeAttributeFilterType } from "./productTypeAttributeFilterType";
import type { ProductTypeAttributeValueType } from "./productTypeAttributeValueType";

/**
 * One attribute of one product type, as the client renders it.
 */
export interface ProductTypeAttribute {
  code: string;
  role: ProductTypeAttributeRole;
  /** The order the type binds it in, which is display order. */
  sort_order: number;
  is_filterable: boolean;
  /** Empty exactly while the attribute is not filterable. */
  filter_type: ProductTypeAttributeFilterType;
  value_type: ProductTypeAttributeValueType;
  /** Empty on everything but a numeric attribute. */
  unit: string;
  /** The codes an enumerated attribute accepts, in their order. */
  enum_values: string[];
}
