/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * marketi
 * OpenAPI spec version: 1
 */

export interface ProductOfferMerchant {
  name: string;
  url: string;
  logoUrl: string;
  phone: string;
}
