/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */

export type ProductTypeAttributeRole =
  (typeof ProductTypeAttributeRole)[keyof typeof ProductTypeAttributeRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProductTypeAttributeRole = {
  common: "common",
  identity: "identity",
  variant: "variant",
} as const;
