/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * marketi
 * OpenAPI spec version: 1
 */
import type { ProductOffer } from "./productOffer";
import type { ProductAttributeList } from "./productAttributeList";
import type { ProductVariantGroup } from "./productVariantGroup";

export interface Product {
  id: string;
  name: string;
  description: string;
  imageUrls: string[];
  isNew: boolean;
  categoryBreadcrumbs: string[];
  offers: ProductOffer[];
  attributes: ProductAttributeList;
  variants: ProductVariantGroup[];
}
