/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * marketi
 * OpenAPI spec version: 1
 */
import type { ProductListItem } from "./productListItem";

export type ProductList = ProductListItem[];
