/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { AttributeValues } from "./attributeValues";

export interface Product {
  id: string;
  name: string;
  product_type_code: string;
  /** @nullable */
  thumbnail_url: string | null;
  attributes: AttributeValues;
  min_price_tetri: number;
  /** The available offers of visible shops the price is drawn from. */
  offers_count: number;
  created_at: string;
}
