/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { Product } from "./product";
import type { Facet } from "./facet";
import type { Range } from "./range";

export interface ProductList {
  products: Product[];
  facets: Facet[];
  /** One per range-filtered attribute the matching set states. */
  ranges: Range[];
  /** The matching products, of which `products` is one page. */
  total: number;
  /**
   * The bounds of the matching set, which the price filter narrows like
any other filter. Null where nothing matched.

   * @nullable
   */
  min_price_tetri: number | null;
  /** @nullable */
  max_price_tetri: number | null;
  /** Absent on the last page. */
  next_cursor?: string;
}
