/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { AttributeValues } from "./attributeValues";
import type { Offer } from "./offer";
import type { Sibling } from "./sibling";

export interface ProductDetail {
  id: string;
  name: string;
  product_type_code: string;
  /** The product type's axis codes, in picker order. */
  variant_attributes: string[];
  attributes: AttributeValues;
  description: string;
  /** @nullable */
  thumbnail_url: string | null;
  picture_urls: string[];
  offers: Offer[];
  siblings: Sibling[];
}
