/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * marketi
 * OpenAPI spec version: 1
 */
import type { ProductAttribute } from "./productAttribute";

export interface ProductAttributeGroup {
  id: string;
  label: string;
  attributes: ProductAttribute[];
}
