/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * marketi
 * OpenAPI spec version: 1
 */

export interface ProductListItem {
  id: number;
  slug: string;
  name: string;
  minPriceTetri: number;
  offersCount: number;
  imageUrls: string[];
  isNew: boolean;
}
