/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */

/**
 * What a numeric attribute spans over the matching set, which its own
bound narrows like any other filter.

 */
export interface Range {
  attribute_code: string;
  min: number;
  max: number;
}
