/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * marketi
 * OpenAPI spec version: 1
 */
import type { ProductList } from "./productList";
import type { SearchFilter } from "./searchFilter";
import type { SearchCategory } from "./searchCategory";

export interface SearchResponse {
  title: string;
  products: ProductList;
  filters: SearchFilter[];
  categories: SearchCategory[];
  /** @nullable */
  next: string | null;
}
