/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * marketi
 * OpenAPI spec version: 1
 */
import type { SearchSuggestion } from "./searchSuggestion";

/**
 * Подсказки содержат ID, отображаемое название и тип сущности,
к которой они относятся. Актуальный набор типов сущностей указан
в схеме подсказки

 */
export type SearchSuggestionResponseResponse = SearchSuggestion;
