/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * marketi
 * OpenAPI spec version: 1
 */
import type { SearchProductListItem } from "./searchProductListItem";
import type { SearchFilter } from "./searchFilter";
import type { SearchCategory } from "./searchCategory";
import type { Cursor } from "./cursor";

export interface SearchResponse {
  title: string;
  products: SearchProductListItem[];
  filters: SearchFilter[];
  categories: SearchCategory[];
  cursor: Cursor;
}
