/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * marketi
 * OpenAPI spec version: 1
 */

export type SearchSuggestionItemType =
  (typeof SearchSuggestionItemType)[keyof typeof SearchSuggestionItemType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SearchSuggestionItemType = {
  product: "product",
  category: "category",
} as const;
