/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * marketi
 * OpenAPI spec version: 1
 */
import type { SearchSuggestionCategory } from "./searchSuggestionCategory";
import type { SearchSuggestionProduct } from "./searchSuggestionProduct";

export interface SearchSuggestion {
  categories: SearchSuggestionCategory[];
  products: SearchSuggestionProduct[];
}
