/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * marketi
 * OpenAPI spec version: 1
 */
import type { SearchSuggestionItemType } from "./searchSuggestionItemType";

export interface SearchSuggestionItem {
  id: string;
  label: string;
  type: SearchSuggestionItemType;
}
