/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * marketi
 * OpenAPI spec version: 1
 */

export interface SearchFilterVariant {
  value: string;
  label: string;
  selected: boolean;
}
