/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * marketi
 * OpenAPI spec version: 1
 */
import type { SearchFilterRange } from "./searchFilterRange";
import type { SearchFilterSelectable } from "./searchFilterSelectable";

export type SearchFilter = SearchFilterRange | SearchFilterSelectable;
