/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * marketi
 * OpenAPI spec version: 1
 */

export type SearchFilterType =
  (typeof SearchFilterType)[keyof typeof SearchFilterType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SearchFilterType = {
  checkbox: "checkbox",
  toggle: "toggle",
  range: "range",
} as const;
