/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * marketi
 * OpenAPI spec version: 1
 */

export type SearchProductsSort =
  (typeof SearchProductsSort)[keyof typeof SearchProductsSort];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SearchProductsSort = {
  popularity: "popularity",
  price: "price",
} as const;
