/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * marketi
 * OpenAPI spec version: 1
 */
import type { ProductSort } from "./productSort";
import type { SortOrder } from "./sortOrder";

export type SearchProductsParams = {
  /**
   * Текст запроса
   */
  q?: string;
  /**
   * Категория поиска. Принимаются только конечные категории
   */
  category?: string;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  sort?: ProductSort;
  /**
   * Направление сортировки. По умолчанию - по убыванию
   */
  sortOrder?: SortOrder;
  cursor?: string;
  /**
   * Фильтры в формате `f[x]=value1,value2`, `f[x]=value1-value2`
   */
  f?: { [key: string]: string };
};
