/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * marketi
 * OpenAPI spec version: 1
 */
import type { SearchResponse } from "./searchResponse";

/**
 * Список продуктов по запросу, подходящих категорий и фильтров
по выбранной или предсказанной категории.

 */
export type SearchResponseResponse = SearchResponse;
