/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * marketi
 * OpenAPI spec version: 1
 */

export type SearchProductsSortOrder =
  (typeof SearchProductsSortOrder)[keyof typeof SearchProductsSortOrder];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SearchProductsSortOrder = {
  asc: "asc",
  desc: "desc",
} as const;
