/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * marketi
 * OpenAPI spec version: 1
 */
import type { ProductSummaryAttribute } from "./productSummaryAttribute";

export type SearchProductListItemAllOf = {
  /** Ключевые атрибуты продукта, отрендеренные по схеме его типа.
Пусты, если категория поиска не определена.
 */
  summary: ProductSummaryAttribute[];
};
