/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * marketi
 * OpenAPI spec version: 1
 */
import type { SearchProductsSort } from "./searchProductsSort";
import type { SearchProductsSortOrder } from "./searchProductsSortOrder";

export type SearchProductsParams = {
  /**
   * Текст запроса
   */
  q?: string;
  /**
   * Категория поиска. Принимаются только конечные категории
   */
  category?: string;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  /**
   * Сортировка. По умолчанию - по популярности
   */
  sort?: SearchProductsSort;
  /**
   * Направление сортировки. По умолчанию - по убыванию
   */
  sortOrder?: SearchProductsSortOrder;
  /**
 * Курсор пагинации для получения следующей страницы.
Возвращается в поле ответа `next`

 */
  cursor?: string;
};
