/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */

/**
 * The shop an offer is from, as it is displayed (DESIGN.md §3.5). `address`
and `phone_number` are empty where the shop states none.

 */
export interface Shop {
  code: string;
  name: string;
  url: string;
  logo_url: string;
  address: string;
  phone_number: string;
}
