/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type { AttributeValues } from "./attributeValues";

export interface Sibling {
  product_id: string;
  /** One entry per axis, null where no shop published it. */
  values: AttributeValues;
  selected: boolean;
}
