const asset = (name: string) => `/assets/geocart/${name}`

export const uiAssets = {
  catalog: asset('icon-catalog.svg'),
  catalogActive: asset('icon-catalog-active.svg'),
  catalogMuted: asset('icon-catalog-muted.svg'),
  catalogPromoPlaystation: asset('catalog-promo-playstation.png'),
  search: asset('icon-search.svg'),
  close: asset('icon-close.svg'),
  closeWhite: asset('icon-close-white.svg'),
  home: asset('icon-home.svg'),
  homeMuted: asset('icon-home-muted.svg'),
  caret: asset('icon-caret.svg'),
  heart: asset('icon-heart.svg'),
  heartFilled: asset('icon-heart-filled.svg'),
  heartOutline: asset('icon-heart-outline.svg'),
  list: asset('icon-list.svg'),
  globe: asset('icon-globe.svg'),
  footerGlobe: asset('icon-footer-globe.svg'),
  footerCaret: asset('icon-footer-caret.svg'),
  checkmark: asset('icon-checkmark.svg'),
  angleDown: asset('icon-angle-down.svg'),
  angleRight: asset('icon-angle-right.svg'),
  angleUp: asset('icon-angle-up.svg'),
  delete: asset('icon-delete.svg'),
  filters: asset('icon-filters.svg'),
  sort: asset('icon-sort.svg'),
  flagGe: asset('flag-ge.svg'),
  flagRu: asset('flag-ru.svg'),
  flagUs: asset('flag-us.svg'),
  categoryShape: asset('category-shape.svg'),
  favoriteShape: asset('favorite-shape.svg'),
  arrowLeft: asset('icon-arrow-left.svg'),
  arrowRight: asset('icon-arrow-right.svg'),
  dotSmall: asset('dot-small.svg'),
  dotMedium: asset('dot-medium.svg'),
  dotLarge: asset('dot-large.svg'),
}
