import * as stylex from "@stylexjs/stylex";

export const productMobileBestOfferStyles = stylex.create({
  bar: {
    display: { default: "none", "@media (max-width: 760px)": "flex" },
    position: "fixed",
    left: 0,
    right: 0,
    bottom:
      "calc(var(--mobile-tabbar-height) + env(safe-area-inset-bottom, 0px))",
    zIndex: 30,
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    minHeight: "var(--product-mobile-offer-height)",
    padding: "12px var(--layout-gutter-mobile)",
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: "var(--color-divider-dark)",
    backgroundColor: "var(--color-bg-dark)",
    boxShadow: "var(--shadow-bottom-bar)",
  },
  content: { minWidth: 0 },
  price: { color: "var(--color-accent-on-dark)" },
  details: { display: "flex", alignItems: "center", gap: 8, minWidth: 0 },
  label: {
    display: "inline-flex",
    alignItems: "center",
    flexShrink: 0,
    gap: 4,
    padding: 0,
    borderWidth: 0,
    backgroundColor: "transparent",
    color: "var(--color-fg-dark-secondary)",
    fontSize: 12,
    lineHeight: "20px",
  },
  merchant: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    minWidth: 0,
    color: "var(--color-fg-on-dark)",
    fontSize: 12,
    fontWeight: 500,
    lineHeight: "20px",
  },
  name: {
    color: "var(--color-fg-on-dark)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
});
