import * as stylex from "@stylexjs/stylex";

export const productBestOfferStyles = stylex.create({
  aside: {
    display: { default: "block", "@media (max-width: 760px)": "none" },
    paddingTop: 8,
    minWidth: 0,
    position: { default: "sticky", "@media (max-width: 900px)": "static" },
    top: 88,
  },
  pricePanel: {
    padding: 16,
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    backgroundColor: "var(--color-bg-secondary)",
  },
  label: {
    margin: 0,
    marginBottom: 4,
    color: "var(--color-fg-secondary)",
    fontSize: 14,
    lineHeight: "20px",
  },
  prices: {
    display: "flex",
    flexWrap: "wrap",
    gap: "4px 12px",
    alignItems: "baseline",
  },
  discount: {
    color: "var(--color-fg-secondary)",
    fontSize: 16,
    lineHeight: "24px",
    whiteSpace: "nowrap",
  },
  merchant: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    marginTop: 2,
    padding: "12px 16px",
    minHeight: 64,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
    backgroundColor: "var(--color-bg-secondary)",
  },
  name: {
    flex: "1 1 auto",
    minWidth: 0,
    fontSize: 16,
    fontWeight: 500,
    lineHeight: "24px",
    overflowWrap: "anywhere",
    letterSpacing: "-0.32px",
  },
  allOffers: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    width: "100%",
    marginTop: 8,
    padding: "12px 16px",
    minHeight: 64,
    borderWidth: 0,
    borderRadius: 12,
    backgroundColor: "var(--color-bg-secondary)",
    color: "var(--color-fg-primary)",
    textAlign: "left",
  },
  storeIcon: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 40,
    height: 40,
    flexShrink: 0,
    borderRadius: 40,
    backgroundColor: "var(--color-bg-primary)",
  },
  allOffersText: {
    display: "flex",
    flexDirection: "column",
    flex: "1 1 auto",
    gap: 0,
    fontSize: 14,
    fontWeight: 500,
    lineHeight: "20px",
  },
  from: { color: "var(--color-fg-secondary)", fontSize: 12, fontWeight: 400 },
});
