import * as stylex from "@stylexjs/stylex";

export const productHeaderStyles = stylex.create({
  header: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    paddingTop: { default: 24, "@media (max-width: 760px)": 16 },
    paddingBottom: 16,
  },
  breadcrumbs: {
    display: "flex",
    flexWrap: { default: "wrap", "@media (max-width: 760px)": "nowrap" },
    overflowX: { default: null, "@media (max-width: 760px)": "auto" },
    scrollbarWidth: "none",
    alignItems: "center",
    gap: 4,
    listStyle: "none",
    padding: 0,
    margin: 0,
    minHeight: 20,
    color: "var(--color-fg-secondary)",
    fontSize: { default: 14, "@media (max-width: 760px)": 12 },
    lineHeight: "20px",
  },
  breadcrumb: { display: "flex", alignItems: "center", gap: 4, flexShrink: 0 },
  title: {
    margin: 0,
    fontSize: { default: 28, "@media (max-width: 760px)": 24 },
    fontWeight: 600,
    lineHeight: { default: "40px", "@media (max-width: 760px)": "32px" },
    letterSpacing: {
      default: "-0.56px",
      "@media (max-width: 760px)": "-0.48px",
    },
    overflowWrap: "anywhere",
  },
  meta: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 8,
    minHeight: 20,
    color: "var(--color-fg-secondary)",
    fontSize: 14,
    lineHeight: "20px",
  },
  actions: { display: "flex", alignItems: "center", flexWrap: "wrap", gap: 16 },
  action: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    borderWidth: 0,
    backgroundColor: {
      default: "transparent",
      "@media (max-width: 760px)": "var(--color-bg-secondary)",
    },
    padding: { default: 0, "@media (max-width: 760px)": "8px 12px" },
    minHeight: { default: 24, "@media (max-width: 760px)": 40 },
    borderRadius: 20,
    color: "var(--color-fg-secondary)",
    fontSize: 14,
    fontWeight: 500,
    lineHeight: "20px",
  },
  status: {
    margin: 0,
    fontSize: 14,
    lineHeight: "20px",
    color: "var(--color-fg-secondary)",
    textAlign: "right",
  },
  desktopOnly: {
    display: { default: "inline-flex", "@media (max-width: 760px)": "none" },
  },
});
