import * as stylex from "@stylexjs/stylex";

export const productTabsStyles = stylex.create({
  container: {
    paddingTop: { default: 8, "@media (max-width: 760px)": 0 },
    paddingBottom: { default: 32, "@media (max-width: 760px)": 8 },
    paddingRight: {
      default: "var(--layout-gutter)",
      "@media (max-width: 760px)": 0,
    },
    scrollMarginTop: { default: 80, "@media (max-width: 760px)": 64 },
  },
  tabs: {
    display: "flex",
    alignItems: "center",
    gap: { default: 2, "@media (max-width: 760px)": 0 },
    minHeight: { default: 48, "@media (max-width: 760px)": 44 },
    padding: 2,
    borderRadius: 40,
    borderTopRightRadius: { default: 40, "@media (max-width: 760px)": 0 },
    borderBottomRightRadius: { default: 40, "@media (max-width: 760px)": 0 },
    backgroundColor: "var(--color-bg-secondary)",
    overflowX: "auto",
    scrollbarWidth: "none",
    overscrollBehaviorX: "contain",
  },
  tab: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    flex: { default: "1 0 0", "@media (max-width: 1180px)": "1 0 auto" },
    minWidth: { default: 0, "@media (max-width: 1180px)": "max-content" },
    gap: 8,
    minHeight: { default: 44, "@media (max-width: 760px)": 40 },
    borderWidth: 0,
    borderRadius: 56,
    padding: "8px 15px",
    backgroundColor: "transparent",
    color: "var(--color-fg-primary)",
    fontSize: 16,
    fontWeight: 500,
    lineHeight: "24px",
    letterSpacing: "-0.32px",
    whiteSpace: "nowrap",
  },
  active: { backgroundColor: "var(--color-bg-primary)" },
  divider: {
    flexShrink: 0,
    width: 2,
    height: 16,
    marginInline: 3,
    borderRadius: 8,
    backgroundColor: "var(--color-divider-light)",
  },
  count: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minWidth: 20,
    height: 20,
    paddingInline: 4,
    borderRadius: 10,
    backgroundColor: "var(--color-danger)",
    color: "var(--color-fg-on-dark)",
    fontSize: 12,
    lineHeight: "20px",
    letterSpacing: 0,
  },
  disabled: { color: "var(--color-fg-secondary)", cursor: "not-allowed" },
  soon: {
    padding: "2px 8px",
    borderRadius: 24,
    backgroundColor: "var(--color-bg-primary)",
    fontSize: 14,
    lineHeight: "20px",
    letterSpacing: 0,
  },
});
