import * as stylex from "@stylexjs/stylex";

export const productOfferRowStyles = stylex.create({
  row: {
    display: "grid",
    gridTemplateColumns: {
      default: "minmax(0, 1fr) minmax(0, 1fr) 264px",
      "@media (max-width: 1180px)": "minmax(0, 1fr) minmax(180px, 0.75fr)",
      "@media (max-width: 760px)": "minmax(0, 1fr) 48px",
    },
    gap: { default: 16, "@media (max-width: 760px)": "6px 16px" },
    alignItems: { default: "start", "@media (max-width: 760px)": "center" },
    minHeight: { default: 125, "@media (max-width: 760px)": 86 },
    paddingBlock: { default: 20, "@media (max-width: 760px)": 12 },
    paddingInline: { default: 0, "@media (max-width: 760px)": 16 },
    marginBottom: { default: 0, "@media (max-width: 760px)": 8 },
    backgroundColor: {
      default: null,
      "@media (max-width: 760px)": "var(--color-bg-secondary)",
    },
    borderRadius: { default: 0, "@media (max-width: 760px)": 16 },
    borderBottomWidth: { default: 1, "@media (max-width: 760px)": 0 },
    borderBottomStyle: "solid",
    borderBottomColor: "var(--color-divider-light)",
  },
  merchant: {
    display: "flex",
    alignItems: "center",
    gap: { default: 16, "@media (max-width: 760px)": 8 },
    minWidth: 0,
    gridColumn: { default: null, "@media (max-width: 760px)": 1 },
    gridRow: { default: null, "@media (max-width: 760px)": 2 },
  },
  merchantInfo: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    minWidth: 0,
  },
  name: {
    fontSize: { default: 18, "@media (max-width: 760px)": 14 },
    fontWeight: { default: 600, "@media (max-width: 760px)": 500 },
    lineHeight: { default: "24px", "@media (max-width: 760px)": "20px" },
    letterSpacing: { default: "-0.36px", "@media (max-width: 760px)": 0 },
    overflowWrap: "anywhere",
  },
  phone: {
    display: { default: "inline-flex", "@media (max-width: 760px)": "none" },
    alignItems: "center",
    gap: 4,
    padding: 0,
    borderWidth: 0,
    backgroundColor: "transparent",
    color: "var(--color-fg-secondary)",
    fontSize: 14,
    fontWeight: 500,
    lineHeight: "20px",
    textAlign: "left",
  },
  details: {
    paddingBlock: 4,
    display: { default: "block", "@media (max-width: 1180px)": "none" },
  },
  learnMore: {
    color: "var(--color-accent)",
    fontSize: 14,
    fontWeight: 500,
    lineHeight: "20px",
  },
  purchase: {
    display: { default: "flex", "@media (max-width: 760px)": "contents" },
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 16,
    paddingTop: 4,
  },
  price: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    paddingTop: { default: 4, "@media (max-width: 760px)": 0 },
    minWidth: 0,
    gridColumn: { default: null, "@media (max-width: 760px)": 1 },
    gridRow: { default: null, "@media (max-width: 760px)": 1 },
  },
  comparison: {
    display: { default: "inline", "@media (max-width: 760px)": "none" },
    color: "var(--color-fg-secondary)",
    fontSize: 12,
    lineHeight: "16px",
  },
  buyLink: {
    gridColumn: { default: null, "@media (max-width: 760px)": 2 },
    gridRow: { default: null, "@media (max-width: 760px)": "1 / 3" },
    width: { default: null, "@media (max-width: 760px)": 48 },
    height: { default: null, "@media (max-width: 760px)": 48 },
    padding: { default: "8px 15px", "@media (max-width: 760px)": 12 },
  },
  buyLabel: {
    display: { default: "inline", "@media (max-width: 760px)": "none" },
  },
  buyIcon: {
    display: { default: "none", "@media (max-width: 760px)": "block" },
  },
});
