/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type {
  CategoryList,
  ListProductSuggestionsParams,
  ListProductsParams,
  ProductDetail,
  ProductList,
  ProductSuggestionList,
  ProductType,
} from "../../models";

import { orvalClient } from "../../../../network/orval-client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const listCategories = (
  options?: SecondParameter<typeof orvalClient<CategoryList>>,
) => {
  return orvalClient<CategoryList>(
    { url: `/api/v1/categories`, method: "GET" },
    options,
  );
};
/**
 * What a card, a filter and a specification table render: the type's
attributes in binding order, each with its value type, unit and the
order an enumerated one's values take. Codes throughout — a label is the
frontend's (DESIGN.md §7.5).

 */
export const getProductType = (
  code: string,
  options?: SecondParameter<typeof orvalClient<ProductType>>,
) => {
  return orvalClient<ProductType>(
    { url: `/api/v1/product-types/${code}`, method: "GET" },
    options,
  );
};
/**
 * Attribute filters are `attr.<code>`, repeated for alternatives:
`attr.color=Black&attr.color=White`. An attribute the binding marks a
range filter takes bounds instead — `attr.refresh_rate.min=60` and
`attr.refresh_rate.max=120`, either one alone. They are not declared
below because the name of such a parameter is an attribute code, which
is data.

 */
export const listProducts = (
  params?: ListProductsParams,
  options?: SecondParameter<typeof orvalClient<ProductList>>,
) => {
  return orvalClient<ProductList>(
    { url: `/api/v1/products`, method: "GET", params },
    options,
  );
};
/**
 * What a search box offers while it is being typed: the products a query
names, closest first, and nothing a card would need.

 */
export const listProductSuggestions = (
  params: ListProductSuggestionsParams,
  options?: SecondParameter<typeof orvalClient<ProductSuggestionList>>,
) => {
  return orvalClient<ProductSuggestionList>(
    { url: `/api/v1/products/suggest`, method: "GET", params },
    options,
  );
};
export const getProduct = (
  id: string,
  options?: SecondParameter<typeof orvalClient<ProductDetail>>,
) => {
  return orvalClient<ProductDetail>(
    { url: `/api/v1/products/${id}`, method: "GET" },
    options,
  );
};
export type ListCategoriesResult = NonNullable<
  Awaited<ReturnType<typeof listCategories>>
>;
export type GetProductTypeResult = NonNullable<
  Awaited<ReturnType<typeof getProductType>>
>;
export type ListProductsResult = NonNullable<
  Awaited<ReturnType<typeof listProducts>>
>;
export type ListProductSuggestionsResult = NonNullable<
  Awaited<ReturnType<typeof listProductSuggestions>>
>;
export type GetProductResult = NonNullable<
  Awaited<ReturnType<typeof getProduct>>
>;
