import * as stylex from "@stylexjs/stylex";

export const productSharedStyles = stylex.create({
  sectionTitle: {
    margin: 0,
    paddingTop: { default: 8, "@media (max-width: 760px)": 16 },
    paddingBottom: 16,
    fontSize: { default: 24, "@media (max-width: 760px)": 18 },
    fontWeight: 600,
    lineHeight: { default: "32px", "@media (max-width: 760px)": "24px" },
    letterSpacing: {
      default: "-0.48px",
      "@media (max-width: 760px)": "-0.36px",
    },
  },
  subtitle: {
    margin: 0,
    fontSize: 16,
    fontWeight: 500,
    lineHeight: "24px",
    letterSpacing: "-0.32px",
  },
  button: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    minHeight: 40,
    padding: "8px 16px",
    borderWidth: 0,
    borderRadius: 34,
    backgroundColor: "var(--color-bg-secondary)",
    color: "var(--color-fg-primary)",
    fontSize: 16,
    fontWeight: 500,
    lineHeight: "24px",
    letterSpacing: "-0.32px",
  },
  buyButton: {
    backgroundColor: {
      default: "var(--color-accent)",
      ":hover": "var(--color-accent-hover)",
    },
    color: "var(--color-fg-on-dark)",
    flexShrink: 0,
    paddingInline: 15,
  },
  textButton: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    padding: 0,
    borderWidth: 0,
    backgroundColor: "transparent",
    color: "var(--color-accent)",
    fontSize: 16,
    fontWeight: 500,
    lineHeight: "24px",
    textAlign: "left",
  },
  mobileBuyButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 48,
    height: 48,
    borderRadius: 34,
    padding: 12,
  },
  buyArrow: { transform: "scaleY(-1)" },
  price: {
    margin: 0,
    color: "var(--color-fg-primary)",
    fontSize: 24,
    fontWeight: 600,
    lineHeight: "32px",
    letterSpacing: "-0.48px",
    overflowWrap: "anywhere",
  },
  bestPrice: { color: "var(--color-accent)" },
  onAccent: { color: "var(--color-fg-on-dark)" },
  muted: { color: "var(--color-fg-secondary)" },
  empty: {
    color: "var(--color-fg-secondary)",
    fontSize: 16,
    lineHeight: "24px",
  },
});
