/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * marketi
 * OpenAPI spec version: 1
 */
import type {
  CategoryListResponseResponse,
  ListProductsParams,
  ListSuggestionsParams,
  ProductListResponseResponse,
  ProductResponseResponse,
  SearchProductsParams,
  SearchResponseResponse,
  SearchSuggestionResponseResponse,
} from "../../models";

import { orvalClient } from "../../../../network/orval-client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Отсортированный список категорий со всеми подкатегориями

 */
export const listCategories = (
  options?: SecondParameter<typeof orvalClient<CategoryListResponseResponse>>,
) => {
  return orvalClient<CategoryListResponseResponse>(
    { url: `/catalog/categories`, method: "GET" },
    options,
  );
};
/**
 * Список популярных продуктов.

 */
export const listProducts = (
  params: ListProductsParams,
  options?: SecondParameter<typeof orvalClient<ProductListResponseResponse>>,
) => {
  return orvalClient<ProductListResponseResponse>(
    { url: `/catalog/products`, method: "GET", params },
    options,
  );
};
/**
 * Детальная карточка продукта

 */
export const getProduct = (
  id: string,
  options?: SecondParameter<typeof orvalClient<ProductResponseResponse>>,
) => {
  return orvalClient<ProductResponseResponse>(
    { url: `/catalog/products/${id}`, method: "GET" },
    options,
  );
};
/**
 * Поиск продуктов по тексту и/или фильтрам.
Продукты всегда возвращаются в рамках одной из категорий для поддержания корректности
фильтров. Также возвращаются возможные категории продуктов и выбранная категория,
по которой происходит поиск.

При запросе с фильтрами всегда необходимо указывать категорию.

Возможные фильтры, их названия и типы полностью определяются тем, что ответил сервер.
Поэтому они не указаны как параметры запроса в схеме. Каждый тип фильтра соотносится типа параметра, который фильтруется.
Каждый фильтр в ответе имеет указатель на то, были ли выбраны какие-то значения для этого фильтра при запросе.
Так на стороне клиента должны отсекаться невалидные значения, сужения фильтров и так далее: логика формирования фильтров
и действующих значений полностью находится на стороне сервера.

Правила наименований фильтров при использовании в запросе:
  - Типы фильтров: `checkbox`, `range`, `toggle`.
  - `checkbox`: фильтры предполагают выбор нескольких предложенных значений.
  В качестве сепаратора значения использовать `,`, например: `brand=Apple,Samsung'
  - `range`: фильтр предполагает выбор из минимального и максимального значения какого-то числового
  параметра для поиска. `min` и `max` из ответа указывают на минимальные и максимальные значения по всему корпусу.
  При применении данного фильтра необходимо **всегда присылать оба значения** в виде: `{selectedMin}-{selectedMax}`,
  заменяя невыбранные границами всего корпуса, которые пришли в ответе.
  - `toggle`: простой фильтр `true/false`. Отправлять как `true/false`.

 */
export const searchProducts = (
  params?: SearchProductsParams,
  options?: SecondParameter<typeof orvalClient<SearchResponseResponse>>,
) => {
  return orvalClient<SearchResponseResponse>(
    { url: `/catalog/search`, method: "GET", params },
    options,
  );
};
/**
 * Подсказки для поиска

 */
export const listSuggestions = (
  params: ListSuggestionsParams,
  options?: SecondParameter<
    typeof orvalClient<SearchSuggestionResponseResponse>
  >,
) => {
  return orvalClient<SearchSuggestionResponseResponse>(
    { url: `/catalog/search/suggest`, method: "GET", params },
    options,
  );
};
