/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * marketi
 * OpenAPI spec version: 1
 */
import type {
  CategoryList,
  ListProductsParams,
  ListSuggestionsParams,
  Product,
  ProductListResponse,
  SearchProductsParams,
  SearchResponse,
  SearchSuggestion,
} from "../../models";

import { orvalClient } from "../../../../network/orval-client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Отсортированный список категорий со всеми подкатегориями

 */
export const listCategories = (
  options?: SecondParameter<typeof orvalClient<CategoryList>>,
) => {
  return orvalClient<CategoryList>(
    { url: `/categories`, method: "GET" },
    options,
  );
};
/**
 * Список популярных продуктов.

 */
export const listProducts = (
  params: ListProductsParams,
  options?: SecondParameter<typeof orvalClient<ProductListResponse>>,
) => {
  return orvalClient<ProductListResponse>(
    { url: `/products`, method: "GET", params },
    options,
  );
};
/**
 * Детальная карточка продукта

 */
export const getProduct = (
  slug: string,
  options?: SecondParameter<typeof orvalClient<Product>>,
) => {
  return orvalClient<Product>(
    { url: `/products/${slug}`, method: "GET" },
    options,
  );
};
/**
 * Поиск продуктов по тексту и/или фильтрам.
Продукты всегда возвращаются в рамках одной из категорий для поддержания корректности
фильтров. Также возвращаются возможные категории продуктов и выбранная категория,
по которой происходит поиск.

При запросе с фильтрами всегда необходимо указывать категорию.

Возможные фильтры, их названия и типы полностью определяются тем, что ответил сервер.
Их нужно указывать как `f[id]=X`, например `f[price]=100-200&f[color]=red,blue`.
Каждый фильтр в ответе имеет указатель на то, были ли выбраны какие-то значения для этого фильтра при запросе.
Так на стороне клиента должны отсекаться невалидные значения, сужения фильтров и так далее: логика формирования фильтров
и действующих значений полностью находится на стороне сервера.

Правила наименований фильтров при использовании в запросе:
  - Типы фильтров: `checkbox`, `range`, `toggle`.
  - `checkbox`: фильтры предполагают выбор нескольких предложенных значений.
  В качестве сепаратора значения использовать `,`, например: `brand=Apple,Samsung'
  - `range`: фильтр предполагает выбор из минимального и максимального значения какого-то числового
  параметра для поиска. `min` и `max` из ответа указывают на минимальные и максимальные значения по всему корпусу.
  При применении данного фильтра необходимо **всегда присылать оба значения** в виде: `{selectedMin}-{selectedMax}`,
  заменяя невыбранные границами всего корпуса, которые пришли в ответе.
  - `toggle`: простой фильтр `true/false`. Отправлять как `true/false`.

 */
export const searchProducts = (
  params?: SearchProductsParams,
  options?: SecondParameter<typeof orvalClient<SearchResponse>>,
) => {
  return orvalClient<SearchResponse>(
    { url: `/search`, method: "GET", params },
    options,
  );
};
/**
 * Подсказки для поиска

 */
export const listSuggestions = (
  params: ListSuggestionsParams,
  options?: SecondParameter<typeof orvalClient<SearchSuggestion>>,
) => {
  return orvalClient<SearchSuggestion>(
    { url: `/search/suggest`, method: "GET", params },
    options,
  );
};
