import * as stylex from "@stylexjs/stylex";

export const compareControlsStyles = stylex.create({
  controls: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    paddingBlock: { default: 16, "@media (max-width: 760px)": 8 },
    borderTopWidth: { default: 1, "@media (max-width: 760px)": 0 },
    borderTopStyle: "solid",
    borderTopColor: "var(--color-divider-light)",
  },
  segment: {
    display: "flex",
    gap: 2,
    padding: 2,
    minHeight: 40,
    borderRadius: 34,
    backgroundColor: "var(--color-bg-secondary)",
    width: { default: "auto", "@media (max-width: 760px)": "100%" },
  },
  option: {
    flex: { default: "0 1 auto", "@media (max-width: 760px)": "1 1 0" },
    minWidth: 0,
    minHeight: 36,
    padding: "6px 12px",
    borderWidth: 0,
    borderRadius: 18,
    backgroundColor: "transparent",
    color: "var(--color-fg-secondary)",
    fontSize: 16,
    fontWeight: 500,
    lineHeight: "24px",
    letterSpacing: "-0.02em",
  },
  selected: {
    backgroundColor: "var(--color-bg-primary)",
    color: "var(--color-fg-primary)",
  },
  deleteButton: {
    display: { default: "inline-flex", "@media (max-width: 760px)": "none" },
    flexShrink: 0,
    alignItems: "center",
    gap: 4,
    minHeight: 40,
    padding: "8px 16px 8px 12px",
    borderWidth: 0,
    borderRadius: 34,
    backgroundColor: "var(--color-bg-secondary)",
    color: "var(--color-fg-primary)",
    fontSize: 16,
    fontWeight: 500,
    lineHeight: "24px",
  },
});
