/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * market
 * OpenAPI spec version: 1
 */
import type {
  CrmAliasList,
  CrmAttributeAlias,
  CrmAttributeAliased,
  CrmAttributeEdit,
  CrmAttributeList,
  CrmAttributeSaved,
  CrmAttributeValues,
  CrmBackfilled,
  CrmBindingEdit,
  CrmBindingList,
  CrmBindingSaved,
  CrmCategory,
  CrmCategoryEdit,
  CrmCategoryList,
  CrmDivergenceList,
  CrmForkList,
  CrmJobRun,
  CrmJobRunCancel,
  CrmJobRunCancelled,
  CrmJobRunList,
  CrmOfferCardResponse,
  CrmOfferEdit,
  CrmOfferList,
  CrmOfferLock,
  CrmOfferReview,
  CrmOverrideList,
  CrmProduct,
  CrmProductList,
  CrmProductLock,
  CrmProductTypeEdit,
  CrmProductTypeList,
  CrmProductTypeSaved,
  CrmScrapeTarget,
  CrmScrapeTargetEdit,
  CrmScrapeTargetList,
  CrmScrapeTargetSaved,
  CrmShop,
  CrmShopEdit,
  CrmShopList,
  CrmSilenceList,
  CrmTaxonomyEdit,
  CrmTaxonomyList,
  CrmTaxonomySaved,
  CrmUnmappedKeyList,
  DeleteCrmShopTaxonomyParams,
  ListCrmJobRunsParams,
  ListCrmOffersParams,
  ListCrmProductForksParams,
  ListCrmProductsParams,
} from "../../models";

import { orvalClient } from "../../../../network/orval-client";
import type { BodyType } from "../../../../network/orval-client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * One page of offers under the shared CRM filter. Every parameter is
optional and narrows; repeating one states alternatives. A parameter
no filter declares is a 400 rather than an ignored typo.

 */
export const listCrmOffers = (
  params?: ListCrmOffersParams,
  options?: SecondParameter<typeof orvalClient<CrmOfferList>>,
) => {
  return orvalClient<CrmOfferList>(
    { url: `/api/v1/crm/offers`, method: "GET", params },
    options,
  );
};
/**
 * Every shop, ordered by code. Codes are data, so they are strings rather
than a fixed list a client would have to be regenerated to learn.

 */
export const listCrmShops = (
  options?: SecondParameter<typeof orvalClient<CrmShopList>>,
) => {
  return orvalClient<CrmShopList>(
    { url: `/api/v1/crm/shops`, method: "GET" },
    options,
  );
};
/**
 * Every attribute, ordered by code. Codes are data, so they are strings
rather than a fixed list a client would have to be regenerated to learn.

 */
export const listCrmAttributes = (
  options?: SecondParameter<typeof orvalClient<CrmAttributeList>>,
) => {
  return orvalClient<CrmAttributeList>(
    { url: `/api/v1/crm/attributes`, method: "GET" },
    options,
  );
};
/**
 * What the shops published for one attribute, over every offer carrying
it, most frequent first. Each value names the canonical matching
currently resolves it to. It scopes by attribute alone, because an alias
does and a narrower screen would under-show what an edit rewrites.

 */
export const listCrmAttributeValues = (
  code: string,
  options?: SecondParameter<typeof orvalClient<CrmAttributeValues>>,
) => {
  return orvalClient<CrmAttributeValues>(
    { url: `/api/v1/crm/attributes/${code}/values`, method: "GET" },
    options,
  );
};
/**
 * Every alias, whatever attribute holds it, ordered by attribute and folded
value. It is how one is found by an operator who does not already know
which attribute carries it; writing and re-pointing one is still the
attribute's.

 */
export const listCrmAliases = (
  options?: SecondParameter<typeof orvalClient<CrmAliasList>>,
) => {
  return orvalClient<CrmAliasList>(
    { url: `/api/v1/crm/aliases`, method: "GET" },
    options,
  );
};
/**
 * What one identity group's rows and offers say about this attribute where
they do not agree. `within` is two shops contradicting each other inside
one configuration; `across` is what separates one configuration from
another, which is what an axis looks like. Most divergent first, and
capped.

 */
export const listCrmAttributeDivergence = (
  code: string,
  options?: SecondParameter<typeof orvalClient<CrmDivergenceList>>,
) => {
  return orvalClient<CrmDivergenceList>(
    { url: `/api/v1/crm/attributes/${code}/divergence`, method: "GET" },
    options,
  );
};
/**
 * Points observed values at one canonical. Each is written under its
folded form, so a value already aliased is re-pointed, and each enqueues
the `rematch` that re-resolves the offers carrying it. An attribute
whose values are not free text is a 400: aliases correct strings.

 */
export const aliasCrmAttributeValues = (
  code: string,
  crmAttributeAlias: BodyType<CrmAttributeAlias>,
  options?: SecondParameter<typeof orvalClient<CrmAttributeAliased>>,
) => {
  return orvalClient<CrmAttributeAliased>(
    {
      url: `/api/v1/crm/attributes/${code}/aliases`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: crmAttributeAlias,
    },
    options,
  );
};
/**
 * One page of job runs, newest first, with the counts of the whole
filtered set beside it. Every parameter is optional and narrows;
repeating one states alternatives.

 */
export const listCrmJobRuns = (
  params?: ListCrmJobRunsParams,
  options?: SecondParameter<typeof orvalClient<CrmJobRunList>>,
) => {
  return orvalClient<CrmJobRunList>(
    { url: `/api/v1/crm/job-runs`, method: "GET", params },
    options,
  );
};
/**
 * Cancels every unfinished run of the named kinds, or every unfinished run
when none is named. A run that has already finished stays as it
finished.

 */
export const cancelCrmJobRuns = (
  crmJobRunCancel: BodyType<CrmJobRunCancel>,
  options?: SecondParameter<typeof orvalClient<CrmJobRunCancelled>>,
) => {
  return orvalClient<CrmJobRunCancelled>(
    {
      url: `/api/v1/crm/job-runs/cancel`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: crmJobRunCancel,
    },
    options,
  );
};
/**
 * Cancels one run. A run that has already finished is a 409, and the work
already being processed is cancelled with it.

 */
export const cancelCrmJobRun = (
  id: string,
  options?: SecondParameter<typeof orvalClient<CrmJobRun>>,
) => {
  return orvalClient<CrmJobRun>(
    { url: `/api/v1/crm/job-runs/${id}/cancel`, method: "POST" },
    options,
  );
};
/**
 * Every scrape target, ordered by shop code and url.
 */
export const listCrmScrapeTargets = (
  options?: SecondParameter<typeof orvalClient<CrmScrapeTargetList>>,
) => {
  return orvalClient<CrmScrapeTargetList>(
    { url: `/api/v1/crm/scrape-targets`, method: "GET" },
    options,
  );
};
/**
 * Creates a target. Its `static_attributes` may only name attributes its
category binds.

 */
export const createCrmScrapeTarget = (
  crmScrapeTargetEdit: BodyType<CrmScrapeTargetEdit>,
  options?: SecondParameter<typeof orvalClient<CrmScrapeTarget>>,
) => {
  return orvalClient<CrmScrapeTarget>(
    {
      url: `/api/v1/crm/scrape-targets`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: crmScrapeTargetEdit,
    },
    options,
  );
};
/**
 * Enqueues a scrape of one target. The worker is what opens the job run,
so the run appears in the listing rather than in this response. A
disabled target is a 409.

 */
export const runCrmScrapeTarget = (
  id: string,
  options?: SecondParameter<typeof orvalClient<void>>,
) => {
  return orvalClient<void>(
    { url: `/api/v1/crm/scrape-targets/${id}/run`, method: "POST" },
    options,
  );
};
/**
 * One offer as its CRM card renders it.
 */
export const getCrmOffer = (
  id: string,
  options?: SecondParameter<typeof orvalClient<CrmOfferCardResponse>>,
) => {
  return orvalClient<CrmOfferCardResponse>(
    { url: `/api/v1/crm/offers/${id}`, method: "GET" },
    options,
  );
};
/**
 * Edits the content a lock protects. A value the type's schema refuses
is nulled and the offer is flagged for review, exactly as the model's
answer is. The edit reaches a product through a re-match.

 */
export const updateCrmOffer = (
  id: string,
  crmOfferEdit: BodyType<CrmOfferEdit>,
  options?: SecondParameter<typeof orvalClient<CrmOfferCardResponse>>,
) => {
  return orvalClient<CrmOfferCardResponse>(
    {
      url: `/api/v1/crm/offers/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: crmOfferEdit,
    },
    options,
  );
};
/**
 * Moves the offer through one review transition. Only the transitions the
card reports are accepted; anything else is a 409.

 */
export const reviewCrmOffer = (
  id: string,
  crmOfferReview: BodyType<CrmOfferReview>,
  options?: SecondParameter<typeof orvalClient<CrmOfferCardResponse>>,
) => {
  return orvalClient<CrmOfferCardResponse>(
    {
      url: `/api/v1/crm/offers/${id}/review`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: crmOfferReview,
    },
    options,
  );
};
/**
 * Locking takes the snapshot unlocking writes back. Price and availability
update on a locked offer either way.

 */
export const lockCrmOffer = (
  id: string,
  crmOfferLock: BodyType<CrmOfferLock>,
  options?: SecondParameter<typeof orvalClient<CrmOfferCardResponse>>,
) => {
  return orvalClient<CrmOfferCardResponse>(
    {
      url: `/api/v1/crm/offers/${id}/lock`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: crmOfferLock,
    },
    options,
  );
};
/**
 * Hands the offer back to the matcher. An offer the matcher would ignore —
one in review, denied, or not yet parsed — is a 409.

 */
export const rematchCrmOffer = (
  id: string,
  options?: SecondParameter<typeof orvalClient<CrmOfferCardResponse>>,
) => {
  return orvalClient<CrmOfferCardResponse>(
    { url: `/api/v1/crm/offers/${id}/rematch`, method: "POST" },
    options,
  );
};
/**
 * The browse tree, ordered by path. A category binds nothing at any
depth: a parent and a leaf are the same kind of thing.

 */
export const listCrmCategories = (
  options?: SecondParameter<typeof orvalClient<CrmCategoryList>>,
) => {
  return orvalClient<CrmCategoryList>(
    { url: `/api/v1/crm/categories`, method: "GET" },
    options,
  );
};
/**
 * Creates the category or edits it; the code is the path and is
immutable. A changed parent carries the subtree's paths with it.

 */
export const saveCrmCategory = (
  code: string,
  crmCategoryEdit: BodyType<CrmCategoryEdit>,
  options?: SecondParameter<typeof orvalClient<CrmCategory>>,
) => {
  return orvalClient<CrmCategory>(
    {
      url: `/api/v1/crm/categories/${code}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: crmCategoryEdit,
    },
    options,
  );
};
/**
 * Deletes a category nothing points at. One with a type mapped to it, a
product attached to it, a mapping or a target naming it, or a child, is
a 409 — categories are RESTRICT parents throughout.

 */
export const deleteCrmCategory = (
  code: string,
  options?: SecondParameter<typeof orvalClient<void>>,
) => {
  return orvalClient<void>(
    { url: `/api/v1/crm/categories/${code}`, method: "DELETE" },
    options,
  );
};
/**
 * Every product type, ordered by code, with the browse categories its
products sit under. A type owns the attribute schema; a category owns
nothing but the tree.

 */
export const listCrmProductTypes = (
  options?: SecondParameter<typeof orvalClient<CrmProductTypeList>>,
) => {
  return orvalClient<CrmProductTypeList>(
    { url: `/api/v1/crm/product-types`, method: "GET" },
    options,
  );
};
/**
 * Creates the type or edits it; the code is the path and is immutable. An
edited name template enqueues the `rename` that rewrites the rows it
names. The category list is read at browse time, so editing it
recomputes nothing.

 */
export const saveCrmProductType = (
  code: string,
  crmProductTypeEdit: BodyType<CrmProductTypeEdit>,
  options?: SecondParameter<typeof orvalClient<CrmProductTypeSaved>>,
) => {
  return orvalClient<CrmProductTypeSaved>(
    {
      url: `/api/v1/crm/product-types/${code}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: crmProductTypeEdit,
    },
    options,
  );
};
/**
 * Deletes a type nothing points at. A binding, a product, an offer, a
target, a mapping or a mapped category is a 409.

 */
export const deleteCrmProductType = (
  code: string,
  options?: SecondParameter<typeof orvalClient<void>>,
) => {
  return orvalClient<void>(
    { url: `/api/v1/crm/product-types/${code}`, method: "DELETE" },
    options,
  );
};
/**
 * The type's bindings, ordered by attribute code, each carrying the role
overrides that amend it.

 */
export const listCrmProductTypeAttributes = (
  code: string,
  options?: SecondParameter<typeof orvalClient<CrmBindingList>>,
) => {
  return orvalClient<CrmBindingList>(
    { url: `/api/v1/crm/product-types/${code}/attributes`, method: "GET" },
    options,
  );
};
/**
 * Binds the attribute to the type or edits the binding, overrides
included: what the body omits is deleted. An override naming an identity
binding, or scoped by an attribute that is not a free-text identity one,
is a 400. The schema it changes enqueues a `rehash`.

 */
export const saveCrmProductTypeAttribute = (
  code: string,
  attributeCode: string,
  crmBindingEdit: BodyType<CrmBindingEdit>,
  options?: SecondParameter<typeof orvalClient<CrmBindingSaved>>,
) => {
  return orvalClient<CrmBindingSaved>(
    {
      url: `/api/v1/crm/product-types/${code}/attributes/${attributeCode}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: crmBindingEdit,
    },
    options,
  );
};
/**
 * Unbinds the attribute, which enqueues a `rehash`.
 */
export const deleteCrmProductTypeAttribute = (
  code: string,
  attributeCode: string,
  options?: SecondParameter<typeof orvalClient<CrmBackfilled>>,
) => {
  return orvalClient<CrmBackfilled>(
    {
      url: `/api/v1/crm/product-types/${code}/attributes/${attributeCode}`,
      method: "DELETE",
    },
    options,
  );
};
/**
 * Every role override, whatever binding holds it, ordered by product type
and attribute code. It is how one is found by an operator who does not
already know where it lives; editing one is still the binding's.

 */
export const listCrmOverrides = (
  options?: SecondParameter<typeof orvalClient<CrmOverrideList>>,
) => {
  return orvalClient<CrmOverrideList>(
    { url: `/api/v1/crm/overrides`, method: "GET" },
    options,
  );
};
/**
 * Every shop taxonomy mapping, ordered by shop and key. It is the finder;
writing one is the shop's.

 */
export const listCrmTaxonomy = (
  options?: SecondParameter<typeof orvalClient<CrmTaxonomyList>>,
) => {
  return orvalClient<CrmTaxonomyList>(
    { url: `/api/v1/crm/taxonomy`, method: "GET" },
    options,
  );
};
/**
 * What the shops publish that no mapping covers, most published first. It
is the operator's queue, not a fault: a key too coarse for any one type
is left unmapped on purpose, and the target's declaration answers for
the offers under it.

 */
export const listCrmUnmappedTaxonomyKeys = (
  options?: SecondParameter<typeof orvalClient<CrmUnmappedKeyList>>,
) => {
  return orvalClient<CrmUnmappedKeyList>(
    { url: `/api/v1/crm/taxonomy/unmapped`, method: "GET" },
    options,
  );
};
/**
 * One shop's mapping, ordered by key.
 */
export const listCrmShopTaxonomy = (
  code: string,
  options?: SecondParameter<typeof orvalClient<CrmTaxonomyList>>,
) => {
  return orvalClient<CrmTaxonomyList>(
    { url: `/api/v1/crm/shops/${code}/taxonomy`, method: "GET" },
    options,
  );
};
/**
 * Maps one of the shop's keys onto a product type and, where the key says
something about where a customer browses, onto a category. Writing one
is idempotent and enqueues the `recompute_categories` that rebuilds the
memberships the shop's offers gave their rows. The key is in the body
because a shop writes it and a path segment cannot carry every shape.

 */
export const saveCrmShopTaxonomy = (
  code: string,
  crmTaxonomyEdit: BodyType<CrmTaxonomyEdit>,
  options?: SecondParameter<typeof orvalClient<CrmTaxonomySaved>>,
) => {
  return orvalClient<CrmTaxonomySaved>(
    {
      url: `/api/v1/crm/shops/${code}/taxonomy`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: crmTaxonomyEdit,
    },
    options,
  );
};
/**
 * Unmaps one key, which returns it to the queue and is a
`recompute_categories` as writing one is.

 */
export const deleteCrmShopTaxonomy = (
  code: string,
  params: DeleteCrmShopTaxonomyParams,
  options?: SecondParameter<typeof orvalClient<CrmBackfilled>>,
) => {
  return orvalClient<CrmBackfilled>(
    { url: `/api/v1/crm/shops/${code}/taxonomy`, method: "DELETE", params },
    options,
  );
};
/**
 * Creates the attribute or edits it, replacing its enum values. A declared
one is a 409. A changed value type or unit, and a removed enum value,
each enqueue a `rehash` of every category that binds it.

 */
export const saveCrmAttribute = (
  code: string,
  crmAttributeEdit: BodyType<CrmAttributeEdit>,
  options?: SecondParameter<typeof orvalClient<CrmAttributeSaved>>,
) => {
  return orvalClient<CrmAttributeSaved>(
    {
      url: `/api/v1/crm/attributes/${code}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: crmAttributeEdit,
    },
    options,
  );
};
/**
 * Deletes an unbound manual attribute. A declared one is a 409, and so is
one a category binds or a stored value carries.

 */
export const deleteCrmAttribute = (
  code: string,
  options?: SecondParameter<typeof orvalClient<void>>,
) => {
  return orvalClient<void>(
    { url: `/api/v1/crm/attributes/${code}`, method: "DELETE" },
    options,
  );
};
/**
 * Creates the shop or edits it. The code is the path and is immutable, and
there is no delete — a shop is disabled instead.

 */
export const saveCrmShop = (
  code: string,
  crmShopEdit: BodyType<CrmShopEdit>,
  options?: SecondParameter<typeof orvalClient<CrmShop>>,
) => {
  return orvalClient<CrmShop>(
    {
      url: `/api/v1/crm/shops/${code}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: crmShopEdit,
    },
    options,
  );
};
/**
 * How often this shop publishes each attribute its offers' categories bind,
over the offers it has past parsing. A shop that never states one, or has
stopped, is what the rate makes visible.

 */
export const listCrmShopSilence = (
  code: string,
  options?: SecondParameter<typeof orvalClient<CrmSilenceList>>,
) => {
  return orvalClient<CrmSilenceList>(
    { url: `/api/v1/crm/shops/${code}/silence`, method: "GET" },
    options,
  );
};
/**
 * Edits one target. There is no delete — a target is disabled, or its
offers lose their delisting owner. A membership is the product type's
and the shop's mapping, so no edit here rebuilds one.

 */
export const saveCrmScrapeTarget = (
  id: string,
  crmScrapeTargetEdit: BodyType<CrmScrapeTargetEdit>,
  options?: SecondParameter<typeof orvalClient<CrmScrapeTargetSaved>>,
) => {
  return orvalClient<CrmScrapeTargetSaved>(
    {
      url: `/api/v1/crm/scrape-targets/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: crmScrapeTargetEdit,
    },
    options,
  );
};
/**
 * One page of product rows, one per configuration. Attribute filters are
`attr.<code>`, repeated for alternatives, and are not declared below
because such a parameter's name is an attribute code, which is data.

 */
export const listCrmProducts = (
  params?: ListCrmProductsParams,
  options?: SecondParameter<typeof orvalClient<CrmProductList>>,
) => {
  return orvalClient<CrmProductList>(
    { url: `/api/v1/crm/products`, method: "GET", params },
    options,
  );
};
/**
 * Per identity group of one product type, the axes some configurations
state and others say nothing about — the shape a role override removes.
Each row names the attribute and the identity values an override is
scoped by, so the editor opens filled in. Widest fork first, and capped.

 */
export const listCrmProductForks = (
  params: ListCrmProductForksParams,
  options?: SecondParameter<typeof orvalClient<CrmForkList>>,
) => {
  return orvalClient<CrmForkList>(
    { url: `/api/v1/crm/products/forks`, method: "GET", params },
    options,
  );
};
/**
 * Deletes one configuration and not its siblings. Its offers keep their
rows, lose their link, and return to `parsed`, so a row with offers is
recreated by the next match — which is why the flow filters on having
none.

 */
export const deleteCrmProduct = (
  id: string,
  options?: SecondParameter<typeof orvalClient<void>>,
) => {
  return orvalClient<void>(
    { url: `/api/v1/crm/products/${id}`, method: "DELETE" },
    options,
  );
};
/**
 * A locked row is the operator's: the pipeline stops overwriting its
content, and its name is no longer recomputed.

 */
export const lockCrmProduct = (
  id: string,
  crmProductLock: BodyType<CrmProductLock>,
  options?: SecondParameter<typeof orvalClient<CrmProduct>>,
) => {
  return orvalClient<CrmProduct>(
    {
      url: `/api/v1/crm/products/${id}/lock`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: crmProductLock,
    },
    options,
  );
};
export type ListCrmOffersResult = NonNullable<
  Awaited<ReturnType<typeof listCrmOffers>>
>;
export type ListCrmShopsResult = NonNullable<
  Awaited<ReturnType<typeof listCrmShops>>
>;
export type ListCrmAttributesResult = NonNullable<
  Awaited<ReturnType<typeof listCrmAttributes>>
>;
export type ListCrmAttributeValuesResult = NonNullable<
  Awaited<ReturnType<typeof listCrmAttributeValues>>
>;
export type ListCrmAliasesResult = NonNullable<
  Awaited<ReturnType<typeof listCrmAliases>>
>;
export type ListCrmAttributeDivergenceResult = NonNullable<
  Awaited<ReturnType<typeof listCrmAttributeDivergence>>
>;
export type AliasCrmAttributeValuesResult = NonNullable<
  Awaited<ReturnType<typeof aliasCrmAttributeValues>>
>;
export type ListCrmJobRunsResult = NonNullable<
  Awaited<ReturnType<typeof listCrmJobRuns>>
>;
export type CancelCrmJobRunsResult = NonNullable<
  Awaited<ReturnType<typeof cancelCrmJobRuns>>
>;
export type CancelCrmJobRunResult = NonNullable<
  Awaited<ReturnType<typeof cancelCrmJobRun>>
>;
export type ListCrmScrapeTargetsResult = NonNullable<
  Awaited<ReturnType<typeof listCrmScrapeTargets>>
>;
export type CreateCrmScrapeTargetResult = NonNullable<
  Awaited<ReturnType<typeof createCrmScrapeTarget>>
>;
export type RunCrmScrapeTargetResult = NonNullable<
  Awaited<ReturnType<typeof runCrmScrapeTarget>>
>;
export type GetCrmOfferResult = NonNullable<
  Awaited<ReturnType<typeof getCrmOffer>>
>;
export type UpdateCrmOfferResult = NonNullable<
  Awaited<ReturnType<typeof updateCrmOffer>>
>;
export type ReviewCrmOfferResult = NonNullable<
  Awaited<ReturnType<typeof reviewCrmOffer>>
>;
export type LockCrmOfferResult = NonNullable<
  Awaited<ReturnType<typeof lockCrmOffer>>
>;
export type RematchCrmOfferResult = NonNullable<
  Awaited<ReturnType<typeof rematchCrmOffer>>
>;
export type ListCrmCategoriesResult = NonNullable<
  Awaited<ReturnType<typeof listCrmCategories>>
>;
export type SaveCrmCategoryResult = NonNullable<
  Awaited<ReturnType<typeof saveCrmCategory>>
>;
export type DeleteCrmCategoryResult = NonNullable<
  Awaited<ReturnType<typeof deleteCrmCategory>>
>;
export type ListCrmProductTypesResult = NonNullable<
  Awaited<ReturnType<typeof listCrmProductTypes>>
>;
export type SaveCrmProductTypeResult = NonNullable<
  Awaited<ReturnType<typeof saveCrmProductType>>
>;
export type DeleteCrmProductTypeResult = NonNullable<
  Awaited<ReturnType<typeof deleteCrmProductType>>
>;
export type ListCrmProductTypeAttributesResult = NonNullable<
  Awaited<ReturnType<typeof listCrmProductTypeAttributes>>
>;
export type SaveCrmProductTypeAttributeResult = NonNullable<
  Awaited<ReturnType<typeof saveCrmProductTypeAttribute>>
>;
export type DeleteCrmProductTypeAttributeResult = NonNullable<
  Awaited<ReturnType<typeof deleteCrmProductTypeAttribute>>
>;
export type ListCrmOverridesResult = NonNullable<
  Awaited<ReturnType<typeof listCrmOverrides>>
>;
export type ListCrmTaxonomyResult = NonNullable<
  Awaited<ReturnType<typeof listCrmTaxonomy>>
>;
export type ListCrmUnmappedTaxonomyKeysResult = NonNullable<
  Awaited<ReturnType<typeof listCrmUnmappedTaxonomyKeys>>
>;
export type ListCrmShopTaxonomyResult = NonNullable<
  Awaited<ReturnType<typeof listCrmShopTaxonomy>>
>;
export type SaveCrmShopTaxonomyResult = NonNullable<
  Awaited<ReturnType<typeof saveCrmShopTaxonomy>>
>;
export type DeleteCrmShopTaxonomyResult = NonNullable<
  Awaited<ReturnType<typeof deleteCrmShopTaxonomy>>
>;
export type SaveCrmAttributeResult = NonNullable<
  Awaited<ReturnType<typeof saveCrmAttribute>>
>;
export type DeleteCrmAttributeResult = NonNullable<
  Awaited<ReturnType<typeof deleteCrmAttribute>>
>;
export type SaveCrmShopResult = NonNullable<
  Awaited<ReturnType<typeof saveCrmShop>>
>;
export type ListCrmShopSilenceResult = NonNullable<
  Awaited<ReturnType<typeof listCrmShopSilence>>
>;
export type SaveCrmScrapeTargetResult = NonNullable<
  Awaited<ReturnType<typeof saveCrmScrapeTarget>>
>;
export type ListCrmProductsResult = NonNullable<
  Awaited<ReturnType<typeof listCrmProducts>>
>;
export type ListCrmProductForksResult = NonNullable<
  Awaited<ReturnType<typeof listCrmProductForks>>
>;
export type DeleteCrmProductResult = NonNullable<
  Awaited<ReturnType<typeof deleteCrmProduct>>
>;
export type LockCrmProductResult = NonNullable<
  Awaited<ReturnType<typeof lockCrmProduct>>
>;
