import * as stylex from "@stylexjs/stylex";

export const searchFiltersPageStyles = stylex.create({
  page: {
    width: "100%",
    maxWidth: {
      default: 480,
      "@media (max-width: 760px)": "none",
    },
    minHeight: "100vh",
    marginInline: "auto",
    backgroundColor: "var(--color-bg-primary)",
  },
  topbar: {
    display: "flex",
    alignItems: "center",
    minHeight: 56,
    padding: "8px 16px",
  },
  title: {
    flex: "1 1 auto",
    margin: 0,
    fontSize: 20,
    fontWeight: 600,
    lineHeight: "24px",
  },
  closeButton: {
    flex: "0 0 auto",
    backgroundColor: "var(--color-bg-secondary)",
  },
  list: {
    display: "flex",
    flexDirection: "column",
    padding: "0 16px 32px",
  },
  filterGroup: {
    width: "100%",
  },
  filterHeader: {
    display: "flex",
    width: "100%",
    minHeight: 47,
    alignItems: "center",
    gap: 8,
    padding: "12px 0 11px",
    borderWidth: 0,
    backgroundColor: "var(--color-bg-primary)",
    color: "var(--color-fg-secondary)",
    fontSize: 14,
    lineHeight: "20px",
    textAlign: "left",
  },
  filterHeaderText: {
    flex: "1 1 auto",
  },
  filterBody: {
    paddingBottom: 16,
  },
  filterBodyWithTags: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  rangePair: {
    display: "flex",
    gap: 8,
    alignItems: "center",
  },
  inputValue: {
    display: "flex",
    height: 40,
    flex: "1 1 0",
    alignItems: "center",
    minWidth: 0,
    padding: "8px 12px",
    overflow: "hidden",
    borderRadius: 8,
    backgroundColor: "var(--color-bg-secondary)",
    color: "var(--color-fg-primary)",
    fontSize: 16,
    lineHeight: "24px",
    whiteSpace: "nowrap",
  },
  mutedInputValue: {
    color: "var(--color-fg-secondary)",
  },
  tags: {
    display: "flex",
    flexWrap: "wrap",
    gap: 4,
    alignItems: "center",
  },
  filterTag: {
    display: "inline-flex",
    height: 32,
    alignItems: "center",
    justifyContent: "center",
    padding: "6px 12px",
    borderWidth: 0,
    borderRadius: 24,
    backgroundColor: "var(--color-bg-secondary)",
    color: "var(--color-fg-primary)",
    fontSize: 14,
    fontWeight: 500,
    lineHeight: "20px",
    whiteSpace: "nowrap",
  },
  selectedTag: {
    backgroundColor: "var(--color-bg-dark)",
    color: "var(--color-fg-on-dark)",
  },
  divider: {
    height: 1,
    backgroundColor: "var(--color-divider-light)",
  },
});
