import * as stylex from "@stylexjs/stylex";

export const searchPageStyles = stylex.create({
  surfaceSection: {
    backgroundColor: "var(--color-bg-primary)",
  },
  content: {
    display: {
      default: "flex",
      "@media (max-width: 760px)": "block",
    },
    alignItems: "flex-start",
    gap: 32,
    paddingTop: 8,
    paddingRight: {
      default: "var(--layout-gutter)",
      "@media (max-width: 760px)": 0,
    },
    paddingBottom: {
      default: 64,
      "@media (max-width: 760px)": 40,
    },
    paddingLeft: {
      default: "var(--layout-gutter)",
      "@media (max-width: 760px)": 0,
    },
  },
  desktopFilters: {
    display: {
      default: "flex",
      "@media (max-width: 760px)": "none",
    },
    width: 264,
    flex: "0 0 264px",
    flexDirection: "column",
  },
  resultsPane: {
    display: "flex",
    minWidth: 0,
    flex: "1 1 auto",
    flexDirection: "column",
  },
  header: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    paddingTop: {
      default: 24,
      "@media (max-width: 760px)": 16,
    },
    paddingBottom: {
      default: 16,
      "@media (max-width: 760px)": 8,
    },
  },
  breadcrumbs: {
    display: "flex",
    gap: 4,
    alignItems: "center",
    minHeight: 20,
    overflowX: "auto",
    color: "var(--color-fg-secondary)",
    fontSize: 12,
    lineHeight: "20px",
    scrollbarWidth: "none",
    whiteSpace: "nowrap",
    "::-webkit-scrollbar": {
      display: "none",
    },
  },
  breadcrumbIcon: {
    width: 16,
    height: 16,
    flex: "0 0 auto",
    objectFit: "contain",
  },
  breadcrumbLink: {
    flex: "0 0 auto",
  },
  eyebrow: {
    margin: 0,
    color: "var(--color-fg-secondary)",
    fontSize: 12,
    lineHeight: "20px",
  },
  title: {
    maxWidth: {
      default: 760,
      "@media (max-width: 760px)": "none",
    },
    margin: 0,
    color: "var(--color-fg-primary)",
    fontSize: {
      default: 36,
      "@media (max-width: 760px)": 24,
    },
    fontWeight: 600,
    lineHeight: {
      default: "44px",
      "@media (max-width: 760px)": "32px",
    },
    letterSpacing: 0,
  },
  categoryStrip: {
    display: "flex",
    gap: 8,
    width: "100%",
    maxWidth: {
      default: "var(--layout-max-width)",
      "@media (max-width: 760px)": "none",
    },
    marginInline: "auto",
    overflowX: "auto",
    scrollbarWidth: "none",
    padding: {
      default: "8px var(--layout-gutter) 16px",
      "@media (max-width: 760px)": "8px 0 16px var(--layout-gutter-mobile)",
    },
    "::-webkit-scrollbar": {
      display: "none",
    },
  },
  categoryPill: {
    display: "inline-flex",
    flex: "0 0 auto",
    alignItems: "center",
    gap: 12,
    height: 64,
    padding: "8px 24px 8px 8px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "transparent",
    borderRadius: 16,
    backgroundColor: "var(--color-bg-secondary)",
    color: "var(--color-fg-primary)",
    fontSize: 16,
    fontWeight: 500,
    lineHeight: "24px",
  },
  selectedCategoryPill: {
    borderColor: "var(--color-divider-soft)",
    backgroundColor: "var(--color-bg-primary)",
    boxShadow: "0 2px 4px rgb(0 0 0 / 6%)",
  },
  categoryThumb: {
    display: "flex",
    width: 48,
    height: 48,
    flex: "0 0 auto",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    borderRadius: 8,
    backgroundColor: "var(--color-bg-secondary)",
  },
  categoryThumbImage: {
    width: "100%",
    height: "100%",
    objectFit: "contain",
    mixBlendMode: "darken",
  },
  controls: {
    display: "flex",
    justifyContent: "space-between",
    gap: 8,
    alignItems: "center",
    width: "100%",
    overflowX: "auto",
    scrollbarWidth: "none",
    padding: {
      default: "8px 0 16px",
      "@media (max-width: 760px)": "8px 0 16px var(--layout-gutter-mobile)",
    },
    "::-webkit-scrollbar": {
      display: "none",
    },
  },
  controlsMain: {
    display: "flex",
    minWidth: {
      default: 0,
      "@media (max-width: 760px)": "max-content",
    },
    flex: {
      default: "1 1 auto",
      "@media (max-width: 760px)": "0 0 auto",
    },
    gap: {
      default: 16,
      "@media (max-width: 760px)": 8,
    },
    alignItems: "center",
  },
  actionGroup: {
    display: "flex",
    flex: "0 0 auto",
    gap: 4,
    alignItems: "center",
  },
  actionButton: {
    display: "inline-flex",
    minWidth: 48,
    height: {
      default: 40,
      "@media (max-width: 760px)": 32,
    },
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    padding: "4px 12px",
    borderWidth: 0,
    borderRadius: 34,
    backgroundColor: "var(--color-bg-secondary)",
  },
  sortButton: {
    color: "var(--color-fg-primary)",
    fontSize: 16,
    fontWeight: 500,
    lineHeight: "24px",
  },
  sortButtonText: {
    display: {
      default: "inline",
      "@media (max-width: 760px)": "none",
    },
    whiteSpace: "nowrap",
  },
  sortButtonCaret: {
    display: {
      default: "block",
      "@media (max-width: 760px)": "none",
    },
    width: 12,
    height: 12,
  },
  mobileFilterButton: {
    display: {
      default: "none",
      "@media (max-width: 760px)": "inline-flex",
    },
  },
  selectedFilters: {
    display: "flex",
    flex: "0 0 auto",
    gap: 4,
    alignItems: "center",
  },
  selectedFilter: {
    display: "inline-flex",
    height: 40,
    flex: "0 0 auto",
    alignItems: "center",
    gap: 4,
    padding: "8px 12px 8px 16px",
    borderWidth: 0,
    borderRadius: 34,
    backgroundColor: "var(--color-bg-secondary)",
    color: "var(--color-fg-primary)",
    fontSize: 16,
    fontWeight: 500,
    lineHeight: "24px",
    whiteSpace: "nowrap",
  },
  viewSegment: {
    display: {
      default: "flex",
      "@media (max-width: 760px)": "none",
    },
    flex: "0 0 auto",
    gap: 2,
    alignItems: "center",
    height: 40,
    padding: 2,
    borderRadius: 34,
    backgroundColor: "var(--color-bg-secondary)",
  },
  viewButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 36,
    height: 36,
    borderRadius: 18,
  },
  activeViewButton: {
    backgroundColor: "var(--color-bg-primary)",
  },
  resultsGrid: {
    maxWidth: "none",
    gridTemplateColumns: {
      default: "repeat(4, minmax(0, 1fr))",
      "@media (max-width: 1180px)": "repeat(3, minmax(0, 1fr))",
      "@media (max-width: 760px)": "repeat(2, minmax(0, 1fr))",
    },
    justifyContent: "stretch",
    paddingRight: {
      default: 0,
      "@media (max-width: 760px)": 8,
    },
    paddingLeft: {
      default: 0,
      "@media (max-width: 760px)": 8,
    },
  },
  selectedFilterCount: {
    color: "var(--color-fg-secondary)",
    fontSize: 16,
    lineHeight: "24px",
  },
  sheetOverlay: {
    position: "fixed",
    inset: 0,
    zIndex: 90,
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "center",
    backgroundColor: "var(--color-overlay)",
  },
  sortSheet: {
    display: "flex",
    width: "100%",
    maxWidth: {
      default: 480,
      "@media (max-width: 760px)": "none",
    },
    flexDirection: "column",
    padding: "16px 0",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--color-divider-light)",
    borderBottomWidth: 0,
    borderRadius: "24px 24px 0 0",
    backgroundColor: "var(--color-bg-primary)",
    boxShadow: "var(--shadow-dropdown)",
  },
  sortTitleRow: {
    display: "flex",
    alignItems: "center",
    minHeight: 40,
    padding: "8px 16px",
  },
  sortTitle: {
    margin: 0,
    fontSize: 20,
    fontWeight: 600,
    lineHeight: "24px",
  },
  sortOptions: {
    display: "flex",
    flexDirection: "column",
    paddingBottom: 16,
  },
  sortOption: {
    display: "flex",
    minHeight: 40,
    alignItems: "center",
    gap: 8,
    padding: "8px 16px",
    borderWidth: 0,
    backgroundColor: "transparent",
    color: "var(--color-fg-primary)",
    fontSize: 16,
    fontWeight: 500,
    lineHeight: "24px",
    textAlign: "left",
  },
  sortOptionText: {
    flex: "1 1 auto",
  },
  sortFooter: {
    padding: "0 16px",
  },
  sortCancel: {
    width: "100%",
    height: 40,
    padding: "8px 16px",
    borderWidth: 0,
    borderRadius: 34,
    backgroundColor: "var(--color-bg-secondary)",
    color: "var(--color-fg-secondary)",
    fontSize: 16,
    fontWeight: 500,
    lineHeight: "24px",
  },
});
